apiVersion: v1
kind: Secret
metadata:
  name: {{ self.gitlab-ce__fullname() }}
  labels:
    app: {{ self.gitlab-ce__fullname() }}
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    release: "{{ Release.Name }}"
    heritage: "{{ Release.Service }}"
type: Opaque
data:
  {%- if Values.gitlabRootPassword %}
  # Defaulting to a non-sensical value to silence b64enc warning. We'll never
  # actually use this default due to the if statement.
  gitlab-root-password: {{ Values.gitlabRootPassword | default("ignore", true) | b64enc() | quote() }}
  {%- endif %}
  db-user: {{ Values.postgresql.postgresUser | b64enc() | quote() }}
  db-password: {{ Values.postgresql.postgresPassword | b64enc() | quote() }}
  redis-password: {{ Values.redis.redisPassword | b64enc() | quote() }}
