
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: test-namerd
    chart: "namerd-0.2.0"
    heritage: "namerd"
    release: "test"
  name: test-namerd-config
data:
  config.yaml: |-
    admin:
      ip: 0.0.0.0
      port: 9991
    storage:
      kind: io.l5d.k8s
      experimental: true
    namers:
      - kind: io.l5d.k8s
        host: 127.0.0.1
        port: 8001
    interfaces:
      - kind: io.l5d.thriftNameInterpreter
        ip: 0.0.0.0
        port: 4100
      - kind: io.l5d.httpController
        ip: 0.0.0.0
        port: 4180


---

apiVersion: v1
kind: Service
metadata:
  name: test-namerd
  labels:
    chart: "namerd-0.2.0"
spec:
  type: ClusterIP
  ports:
  - name: sync
    port: 4100
  - name: api
    port: 4180
  - name: admin
    port: 9991
  selector:
    app: test-namerd


---

metadata:
  name: d-tab.l5d.io
apiVersion: extensions/v1beta1
kind: ThirdPartyResource
description: stores dtabs used by Buoyant's `namerd` service
versions:
  - name: v1alpha1 # Do not change this value as it hardcoded in Namerd and doesn't work with other value.


---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test-namerd
  labels:
    app: test-namerd
    chart: "namerd-0.2.0"
    heritage: "namerd"
    release: "test"
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: test-namerd
    spec:
      volumes:
      - name: test-namerd-config
        configMap:
          name: "test-namerd-config"
      containers:
      - name: test-namerd
        image: "buoyantio/namerd:0.9.1"
        imagePullPolicy: "IfNotPresent"
        args:
        - /io.buoyant/namerd/config/config.yaml
        ports:
        - name: sync
          containerPort: 4100
        - name: api
          containerPort: 4180
        volumeMounts:
        - name: "test-namerd-config"
          mountPath: "/io.buoyant/namerd/config"
          readOnly: true
        resources:
            limits: {cpu: 500m, memory: 512Mi}
            requests: {cpu: 0, memory: 512Mi}
      - name: kubectl
        image: "buoyantio/kubectl:v1.4.0"
        imagePullPolicy: "IfNotPresent"
        args:
        - "proxy"
        - "-p"
        - "8001"
        resources:
            requests: {cpu: 0, memory: 32Mi}