{%- if Values.rbac.create -%}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app: {{ self.kube2iam__name() }}
    chart: {{ Chart.Name }}-{{ Chart.Version }}
    heritage: {{ Release.Service }}
    release: {{ Release.Name }}
  name: {{ self.kube2iam__fullname() }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ self.kube2iam__fullname() }}
subjects:
  - kind: ServiceAccount
    name: {{ self.kube2iam__fullname() }}
    namespace: {{ Release.Namespace }}
{%- endif -%}
