{%- if Values.rbac.create -%}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ self.kube2iam__name() }}
    chart: {{ Chart.Name }}-{{ Chart.Version }}
    heritage: {{ Release.Service }}
    release: {{ Release.Name }}
  name: {{ self.kube2iam__fullname() }}
{%- endif -%}
