apiVersion: v1
kind: Service
metadata:
  name: {{ self.redis__fullname() }}
  labels:
    app: {{ self.redis__fullname() }}
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    release: "{{ Release.Name }}"
    heritage: "{{ Release.Service }}"
{%- if Values.metrics.enabled %}
  annotations:
{{ toYaml(Values.metrics.annotations) | indent(4) }}
{%- endif %}
spec:
  type: {{ Values.serviceType }}
  ports:
  - name: redis
    port: 6379
    targetPort: redis
  selector:
    app: {{ self.redis__fullname() }}
