{%- if Values.persistence.dataDir.enabled -%}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ self.minecraft__fullname() }}-datadir
  labels:
    app: {{ self.minecraft__fullname() }}
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    release: "{{ Release.Name }}"
    heritage: "{{ Release.Service }}"
  annotations:
  {%- if Values.persistence.storageClass %}
    volume.beta.kubernetes.io/storage-class: {{ Values.persistence.storageClass | quote() }}
  {%- else %}
    volume.alpha.kubernetes.io/storage-class: default
  {%- endif %}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ Values.persistence.dataDir.Size | quote() }}
{%- if Values.persistence.storageClass %}
{%- if ("-"==Values.persistence.storageClass) %}
  storageClassName: ""
{%- else %}
  storageClassName: "{{ Values.persistence.storageClass }}"
{%- endif %}
{%- endif %}
{%- endif -%}
