apiVersion: v1
kind: Service
metadata:
  name: {{ self.minecraft__fullname() }}
  labels:
    app: {{ self.minecraft__fullname() }}
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    release: "{{ Release.Name }}"
    heritage: "{{ Release.Service }}"
spec:
  type: {{ Values.minecraftServer.serviceType }}
  ports:
  - name: minecraft
    port: 25565
    targetPort: minecraft
    protocol: TCP
  selector:
    app: {{ self.minecraft__fullname() }}
