{%- if Values.minecraftServer.rcon.enabled | default("", true) %}
apiVersion: v1
kind: Service
metadata:
  name: "{{ self.minecraft__fullname() }}-rcon"
  labels:
    app: {{ self.minecraft__fullname() }}
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    release: "{{ Release.Name }}"
    heritage: "{{ Release.Service }}"
spec:
  type: {{ Values.minecraftServer.rcon.serviceType }}
  ports:
  - name: rcon
    port: {{ Values.minecraftServer.rcon.port }}
    targetPort: rcon
    protocol: TCP
  selector:
    app: {{ self.minecraft__fullname() }}
{%- endif %}
