apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ self.worker-fullname() }}
  labels:
    heritage: {{ Release.Service | quote() }}
    release: {{ Release.Name | quote() }}
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    component: "{{ Release.Name }}-{{ Values.Worker.Component }}"
spec:
  replicas: {{ Values.Worker.Replicas | default(1, true) }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      component: "{{ Release.Name }}-{{ Values.Worker.Component }}"
  template:
    metadata:
      labels:
        heritage: {{ Release.Service | quote() }}
        release: {{ Release.Name | quote() }}
        chart: "{{ Chart.Name }}-{{ Chart.Version }}"
        component: "{{ Release.Name }}-{{ Values.Worker.Component }}"
    spec:
      containers:
        - name: {{ self.worker-fullname() }}
          image: "{{ Values.Worker.Image }}:{{ Values.Worker.ImageTag }}"
          command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://{{ self.master-fullname() }}:{{ Values.Master.ServicePort }}", "--webui-port", "{{ Values.Worker.ContainerPort }}"]
          ports:
            - containerPort: {{ Values.Worker.ContainerPort }}
          resources:
            requests:
              cpu: "{{ Values.Worker.Cpu }}"
              memory: "{{ Values.Worker.Memory }}"
          env:
          - name: SPARK_DAEMON_MEMORY
            value: {{ Values.Worker.DaemonMemory | default("1g", true) | quote() }}
          - name: SPARK_WORKER_MEMORY
            value: {{ Values.Worker.ExecutorMemory | default("1g", true) | quote() }}
