apiVersion: v1
kind: Service
metadata:
  name: {{ self.fullname() }}
  labels:
    app: {{ self.fullname() }}
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    release: "{{ Release.Name }}"
    heritage: "{{ Release.Service }}"
spec:
  type: {{ Values.serviceType }}
  {%- if Values.serviceType=="LoadBalancer" %}
  loadBalancerIP: {{ Values.ghostLoadBalancerIP | default("", true) }}
  {%- endif %}
  ports:
  - name: http
    port: {{ Values.ghostPort | default("80", true) }}
    targetPort: http
  selector:
    app: {{ self.fullname() }}
