apiVersion: v1
kind: Service
metadata:
  name: {{ self.rabbitmq__fullname() }}
  labels:
    app: {{ self.rabbitmq__fullname() }}
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    release: "{{ Release.Name }}"
    heritage: "{{ Release.Service }}"
spec:
  type: {{ Values.serviceType }}
  ports:
  - name: epmd
    port: 4369
    targetPort: epmd
  - name: amqp
    port: {{ Values.rabbitmqNodePort | default("5672", true) }}
    targetPort: amqp
  - name: dist
    port: {{ Values.rabbitmqNodePort | default("5672", true) | add(20000) }}
    targetPort: dist
  - name: stats
    port: {{ Values.rabbitmqManagerPort | default("15672", true) }}
    targetPort: stats
  selector:
    app: {{ self.rabbitmq__fullname() }}
