apiVersion: v1
kind: Secret
metadata:
  name: {{ self.fullname() }}
  labels:
    app: {{ self.fullname() }}
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    release: "{{ Release.Name }}"
    heritage: "{{ Release.Service }}"
type: Opaque
data:
 access-key : {{ Values.sysdig.AccessKey | default("MISSING", true) | b64enc() | quote() }}
 tags : {{ Values.sysdig.AgentTags | default("", true) | b64enc() | quote() }}
