apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ self.etcd-operator__fullname() }}
  labels:
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    app: "{{ self.etcd-operator__fullname() }}"
    heritage: "{{ Release.Service }}"
    release: "{{ Release.Name }}"
spec:
  replicas: {{ Values.replicaCount }}
  template:
    metadata:
      labels:
        chart: "{{ Chart.Name }}-{{ Chart.Version }}"
        app: {{ self.etcd-operator__fullname() }}
        heritage: "{{ Release.Service }}"
        release: "{{ Release.Name }}"
    spec:
{%- if Values.rbac.install %}
      serviceAccountName: {{ self.etcd-operator__fullname() }}
{%- endif %}
      containers:
      - name: {{ Chart.Name }}
        image: "{{ Values.image.repository }}:{{ Values.image.tag }}"
        imagePullPolicy: {{ Values.image.pullPolicy }}
        command:
        - "/usr/local/bin/etcd-operator"
        - "--pv-provisioner={{ Values.cluster.backup.provisioner }}"
{%- for key, value in Values.commandArgs.iteritems() %}
        - "--{{ key }}={{ value }}"
{%- endfor %}
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
{{ toYaml(Values.resources) | indent(12) }}
    {%- if Values.nodeSelector %}
      nodeSelector:
{{ toYaml(Values.nodeSelector) | indent(8) }}
    {%- endif %}
