apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ self.rocketchat__fullname() }}
  labels:
    app: {{ self.rocketchat__name() }}
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    release: "{{ Release.Name }}"
    heritage: "{{ Release.Service }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ self.rocketchat__name() }}
        release: "{{ Release.Name }}"
    spec:
      containers:
      - name: {{ self.rocketchat__fullname() }}
        image: "{{ Values.image }}"
        imagePullPolicy: {{ Values.imagePullPolicy | default("", true) | quote() }}
        env:
        - name: DEPLOY_PLATFORM
          value: helm-chart
        - name: INSTANCE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MONGO_URL
        {%- if Values.mongodb.mongodbUsername %}
          valueFrom:
            secretKeyRef:
              name: {{ self.rocketchat__fullname() }}
              key: mongo-uri
        {%- else %}
          value: mongodb://{{ self.rocketchat__mongodb__fullname() }}:27017/rocketchat
        {%- endif %}
        {%- if Values.host %}
        - name: ROOT_URL
          value: https://{{ Values.host }}
        {%- endif %}
        - name: MAIL_URL
          valueFrom:
            secretKeyRef:
              name: {{ self.rocketchat__fullname() }}
              key: mail-url
        {%- for key, value in Values.config.iteritems() %}
        - name: {{ key }}
          value: {{ value | quote() }}
        {%- endfor %}
        ports:
        - name: http
          containerPort: 3000
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 20
          timeoutSeconds: 5
        resources:
{{ toYaml(Values.resources) | indent(10) }}
        volumeMounts:
        - name: rocket-data
          mountPath: /app/uploads
      volumes:
      - name: rocket-data
      {%- if Values.persistence.enabled %}
        persistentVolumeClaim:
          claimName: {{ self.rocketchat__fullname() }}
      {%- else %}
        emptyDir: {}
      {%- endif %}

