apiVersion: v1
kind: Secret
metadata:
  name: {{ self.rocketchat__fullname() }}
  labels:
    app: {{ self.rocketchat__name() }}
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    release: "{{ Release.Name }}"
    heritage: "{{ Release.Service }}"
type: Opaque
data:
  mail-url: {{ "smtp://%s:%s@%s:%s" | format(Values.config.SMTP_Username,Values.config.SMTP_Password,Values.config.SMTP_Host,Values.config.SMTP_Port) | b64enc() | quote() }}
  {%- if Values.mongodb.mongodbUsername %}
  mongo-uri: {{ "mongodb://%s:%s@%s-mongodb:27017/%s" | format(Values.mongodb.mongodbUsername,Values.mongodb.mongodbPassword,Release.Name,Values.mongodb.mongodbDatabase) | b64enc() | quote() }}
  {%- endif %}
