{%- if Values.rbac.install %}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ self.fullname() }}
  labels:
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    app: "{{ self.name() }}"
    heritage: "{{ Release.Service }}"
    release: "{{ Release.Name }}"
{%- endif %}
