apiVersion: v1
kind: Service
metadata:
  name: {{ self.fullname() }}
  labels:
    app: "{{ self.name() }}"
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    release: "{{ Release.Name }}"
    heritage: "{{ Release.Service }}"
spec:
  ports:
  - name: pushgateway
    port: 56789
    protocol: TCP
    targetPort: pushgateway
  - name: http
    port: 56790
    protocol: TCP
    targetPort: http
  selector:
    app: "{{ self.name() }}"
    release: "{{ Release.Name }}"
