kind: Service
apiVersion: v1
metadata:
  name: {{ self.openvpn__fullname() }}
  namespace: {{ Release.Namespace }}
  labels:
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    type: openvpn
spec:
  ports:
    - name: openvpn
      port: {{ Values.service.externalPort }}
      targetPort: {{ Values.service.internalPort }}
      protocol: {{ Values.openvpn.OVPN_PROTO | upper() }}
  selector:
    app: {{ self.openvpn__fullname() }}
  type: {{ Values.service.type }}
