apiVersion: v1
kind: Secret
metadata:
  name: {{ self.acs-engine-autoscaler__fullname() }}
  labels:
{{ self.acs-engine-autoscaler__labels__standard()  | indent(4) }}
type: Opaque
data:
  azure-sp-app-id: {{ Values.acsenginecluster.azurespappid | default("MISSING", true) | b64enc() | quote() }}
  azure-sp-secret: {{ Values.acsenginecluster.azurespsecret | default("MISSING", true) | b64enc() | quote() }}
  azure-sp-tenant-id: {{ Values.acsenginecluster.azuresptenantid | default("MISSING", true) | b64enc() | quote() }}
  kubeconfig-private-key: {{ Values.acsenginecluster.kubeconfigprivatekey | default("MISSING", true) | b64enc() | quote() }}
  client-private-key: {{ Values.acsenginecluster.clientprivatekey | default("MISSING", true) | b64enc() | quote() }}
  ca-private-key: {{ Values.acsenginecluster.caprivatekey | default("MISSING", true) | b64enc() | quote() }}