apiVersion: v1
kind: Secret
metadata:
  name: "{{ self.fullname-secrets() }}"
  labels:
    app: {{ self.name() }}
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    release: "{{ Release.Name }}"
    heritage: "{{ Release.Service }}"
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
type: Opaque
data:
  collector-url: {{ Values.sumologic.collectorUrl | default("MISSING", true) | b64enc() | quote() }}
