



---

apiVersion: v1
kind: Service
metadata:
  name: test-kapacitor
  labels:
    chart: "kapacitor-0.4.0"
    release: "test"
    heritage: "kapacitor"
    app: test-kapacitor
spec:
  type: ClusterIP
  ports:
  - port: 9092
    targetPort: 9092
    name: api
  selector:
    app: test-kapacitor


---

