{%- if true==Values.chromeDebug.enabled -%}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ self.selenium__chromeDebug__fullname() }}
  labels:
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
spec:
  replicas: {{ Values.chromeDebug.replicas }}
  template:
    metadata:
      labels:
        app: {{ self.selenium__chromeDebug__fullname() }}
        chart: "{{ Chart.Name }}-{{ Chart.Version }}"
        release: "{{ Release.Name }}"
        heritage: "{{ Release.Service }}"
      annotations: 
    spec:
      containers:
        - name: {{ Chart.Name }}
          image: "{{ Values.chromeDebug.image }}:{{ Values.chromeDebug.tag }}"
          imagePullPolicy: {{ Values.chromeDebug.pullPolicy }}
          ports:
            {%- if Values.hub.jmxPort %}
            - containerPort: {{ Values.hub.jmxPort }}
              name: jmx
              protocol: TCP
            {%- endif %}
            - containerPort: 5900 
              name: vnc
          env:
            - name: HUB_PORT_4444_TCP_ADDR
              value: {{ self.selenium__hub__fullname() }}
            - name: HUB_PORT_4444_TCP_PORT
              value: {{ Values.hub.port | quote() }}
            - name: JAVA_OPTS
              value: {{ Values.chromeDebug.javaOpts | default("", true) | quote() }}
            - name: SE_OPTS
              value: {{ Values.chromeDebug.seOpts | default("", true) | quote() }}
            {%- if Values.chromeDebug.chromeVersion %}
            - name: CHROME_VERSION
              value: {{ Values.chromeDebug.chromeVersion | quote() }}
            {%- endif %}
            {%- if Values.chromeDebug.nodeMaxInstances %}
            - name: NODE_MAX_INSTANCES
              value: {{ Values.chromeDebug.nodeMaxInstances | quote() }}
            {%- endif %}
            {%- if Values.chromeDebug.nodeMaxSession %}
            - name: NODE_MAX_SESSION
              value: {{ Values.chromeDebug.nodeMaxSession | quote() }}
            {%- endif %}
            {%- if Values.chromeDebug.nodeRegisterCycle %}
            - name: NODE_REGISTER_CYCLE
              value: {{ Values.chromeDebug.nodeRegisterCycle | quote() }}
            {%- endif %}
            {%- if Values.chromeDebug.nodePort %}
            - name: NODE_PORT
              value: {{ Values.chromeDebug.nodePort | quote() }}
            {%- endif %}
            {%- if Values.chromeDebug.screenWidth %}
            - name: SCREEN_WIDTH
              value: {{ Values.chromeDebug.screenWidth | quote() }}
            {%- endif %}
            {%- if Values.chromeDebug.screenHeight %}
            - name: SCREEN_HEIGHT
              value: {{ Values.chromeDebug.screenHeight | quote() }}
            {%- endif %}
            {%- if Values.chromeDebug.screenDepth %}
            - name: SCREEN_DEPTH
              value: {{ Values.chromeDebug.screenDepth | quote() }}
            {%- endif %}
            {%- if Values.chromeDebug.display %}
            - name: DISPLAY
              value: {{ Values.chromeDebug.display | quote() }}
            {%- endif %}
            {%- if Values.chromeDebug.timeZone %}
            - name: TZ
              value: {{ Values.chromeDebug.timeZone | quote() }}
            {%- endif %}
          volumeMounts:
{%- if Values.chromeDebug.volumeMounts -%}
{{ toYaml(Values.chromeDebug.volumeMounts) | indent(12) }}
{%- endif %}
          resources:
{{ toYaml(Values.chromeDebug.resources) | indent(12) }}
      volumes:
{%- if Values.chromeDebug.volumes -%}
{{ toYaml(Values.chromeDebug.volumes) | indent(8) }}
{%- endif -%}
{%- endif -%}
