{%- if true==Values.firefoxDebug.enabled -%}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ self.selenium__firefoxDebug__fullname() }}
  labels:
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
spec:
  replicas: {{ Values.firefoxDebug.replicas }}
  template:
    metadata:
      labels:
        app: {{ self.selenium__firefoxDebug__fullname() }}
        chart: "{{ Chart.Name }}-{{ Chart.Version }}"
        release: "{{ Release.Name }}"
        heritage: "{{ Release.Service }}"
      annotations: 
    spec:
      containers:
        - name: {{ Chart.Name }}
          image: "{{ Values.firefoxDebug.image }}:{{ Values.firefoxDebug.tag }}"
          imagePullPolicy: {{ Values.firefoxDebug.pullPolicy }}
          ports:
            {%- if Values.firefoxDebug.jmxPort %}
            - containerPort: {{ Values.firefoxDebug.jmxPort }}
              name: jmx
              protocol: TCP
            {%- endif %}
            - containerPort: 5900 
              name: vnc
          env:
            - name: HUB_PORT_4444_TCP_ADDR
              value: {{ self.selenium__hub__fullname() }}
            - name: HUB_PORT_4444_TCP_PORT
              value: {{ Values.hub.port | quote() }}
            - name: JAVA_OPTS
              value: {{ Values.firefoxDebug.javaOpts | default("", true) | quote() }}
            - name: SE_OPTS
              value: {{ Values.firefoxDebug.seOpts | default("", true) | quote() }}
            {%- if Values.firefoxDebug.firefoxVersion %}
            - name: FIREFOX_VERSION
              value: {{ Values.firefoxDebug.firefoxVersion | quote() }}
            {%- endif %}
            {%- if Values.firefoxDebug.nodeMaxInstances %}
            - name: NODE_MAX_INSTANCES
              value: {{ Values.firefoxDebug.nodeMaxInstances | quote() }}
            {%- endif %}
            {%- if Values.firefoxDebug.nodeMaxSession %}
            - name: NODE_MAX_SESSION
              value: {{ Values.firefoxDebug.nodeMaxSession | quote() }}
            {%- endif %}
            {%- if Values.firefoxDebug.nodeRegisterCycle %}
            - name: NODE_REGISTER_CYCLE
              value: {{ Values.firefoxDebug.nodeRegisterCycle | quote() }}
            {%- endif %}
            {%- if Values.firefoxDebug.nodePort %}
            - name: NODE_PORT
              value: {{ Values.firefoxDebug.nodePort | quote() }}
            {%- endif %}
            {%- if Values.firefoxDebug.screenWidth %}
            - name: SCREEN_WIDTH
              value: {{ Values.firefoxDebug.screenWidth | quote() }}
            {%- endif %}
            {%- if Values.firefoxDebug.screenHeight %}
            - name: SCREEN_HEIGHT
              value: {{ Values.firefoxDebug.screenHeight | quote() }}
            {%- endif %}
            {%- if Values.firefoxDebug.screenDepth %}
            - name: SCREEN_DEPTH
              value: {{ Values.firefoxDebug.screenDepth | quote() }}
            {%- endif %}
            {%- if Values.firefoxDebug.display %}
            - name: DISPLAY
              value: {{ Values.firefoxDebug.display | quote() }}
            {%- endif %}
            {%- if Values.firefoxDebug.timeZone %}
            - name: TZ
              value: {{ Values.firefoxDebug.timeZone | quote() }}
            {%- endif %}
          resources:
{{ toYaml(Values.firefoxDebug.resources) | indent(12) }}
{%- endif -%}
