apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ self.selenium__hub__fullname() }}
  labels:
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ self.selenium__hub__fullname() }}
        chart: "{{ Chart.Name }}-{{ Chart.Version }}"
        release: "{{ Release.Name }}"
        heritage: "{{ Release.Service }}"
      annotations: 
    spec:
      containers:
        - name: {{ Chart.Name }}
          image: "{{ Values.hub.image }}:{{ Values.hub.tag }}"
          imagePullPolicy: {{ Values.hub.pullPolicy }}
          ports:
            {%- if Values.hub.jmxPort %}
            - containerPort: {{ Values.hub.jmxPort }}
              name: jmx
              protocol: TCP
            {%- endif %}
            - containerPort: {{ Values.hub.port }}
              name: http
          livenessProbe:
            httpGet:
              path: /grid/console
              port: {{ Values.hub.port }}
            initialDelaySeconds: 30
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /grid/console
              port: {{ Values.hub.port }}
            timeoutSeconds: {{ Values.hub.readinessTimeout }}
          env:
            - name: JAVA_OPTS
              value: {{ Values.hub.javaOpts | default("", true) | quote() }}
            - name: SE_OPTS
              value: {{ Values.hub.seOpts | default("", true) | quote() }}
            {%- if Values.hub.gridNewSessionWaitTimeout %}
            - name: GRID_NEW_SESSION_WAIT_TIMEOUT
              value: {{ Values.hub.gridNewSessionWaitTimeout | quote() }}
            {%- endif %}
            {%- if Values.hub.gridJettyMaxThreads %}
            - name: GRID_JETTY_MAX_THREADS
              value: {{ Values.hub.gridNewSessionWaitTimeout | quote() }}
            {%- endif %}
            {%- if Values.hub.gridNodePolling %}
            - name: GRID_NODE_POLLING
              value: {{ Values.hub.gridNodePolling | quote() }}
            {%- endif %}
            {%- if Values.hub.gridCleanUpCycle %}
            - name: GRID_CLEANUP_CYCLE
              value: {{ Values.hub.gridCleanUpCycle | quote() }}
            {%- endif %}
            {%- if Values.hub.gridTimeout %}
            - name: GRID_TIMEOUT
              value: {{ Values.hub.gridTimeout | quote() }}
            {%- endif %}
            {%- if Values.hub.gridBrowserTimeout %}
            - name: GRID_BROWSER_TIMEOUT
              value: {{ Values.hub.gridBrowserTimeout | quote() }}
            {%- endif %}
            {%- if Values.hub.gridMaxSession %}
            - name: GRID_MAX_SESSION
              value: {{ Values.hub.gridMaxSession | quote() }}
            {%- endif %}
            {%- if Values.hub.gridUnregisterIfStillDownAfer %}
            - name: GRID_UNREGISTER_IF_STILL_DOWN_AFTER
              value: {{ Values.hub.gridUnregisterIfStillDownAfer | quote() }}
            {%- endif %}
            {%- if Values.hub.timeZone %}
            - name: TZ
              value: {{ Values.hub.timeZone | quote() }}
            {%- endif %}
          resources:
{{ toYaml(Values.hub.resources) | indent(12) }}
