apiVersion: v1
kind: Service
metadata:
  name: {{ self.kube-ops-view__fullname() }}
{%- if Values.service.annotations %}
  annotations:
{{ toYaml(Values.service.annotations) | indent(4) }}
{%- endif %}
  labels:
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
{%- if Values.service.labels %}
{{ toYaml(Values.service.labels) | indent(4) }}
{%- endif %}
spec:
  type: {{ Values.service.type }}
  ports:
  - port: {{ Values.service.externalPort }}
    targetPort: {{ Values.service.internalPort }}
    protocol: TCP
  selector:
    app: {{ self.kube-ops-view__fullname() }}
