
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: spotify-docker-gc
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        daemonset: spotify-docker-gc
    spec:
      containers:
      - name: spotify-docker-gc
        image: "docker.io/spotify/docker-gc:latest"
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh"]
        args: ["-c", '
          touch /var/log/crond.log &&
          echo "0 0 * * * /docker-gc >> /var/log/crond.log 2>&1" | crontab - &&
          crond -L /var/log/crond.log &&
          tail -f /var/log/crond.log' ]
        env:
        - name: GRACE_PERIOD_SECONDS
          value: "0"
        - name: DOCKER_API_VERSION
          value: ""
        volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
      volumes:
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock