apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ self.datadog__checksd__fullname() }}
  labels:
    app: {{ self.datadog__checksd__fullname() }}
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    release: "{{ Release.Name }}"
    heritage: "{{ Release.Service }}"
data:
{%- if Values.datadog.checksd %}
{{ toYaml(Values.datadog.checksd) | indent(2) }}
{%- endif -%}
