apiVersion: v1
kind: Secret
metadata:
  name: {{ self.datadog__fullname() }}
  labels:
    app: {{ self.datadog__fullname() }}
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    release: "{{ Release.Name }}"
    heritage: "{{ Release.Service }}"
type: Opaque
data:
  api-key: {{ Values.datadog.apiKey | default("MISSING", true) | b64enc() | quote() }}
