{%- if Values.deployment.enabled %}
apiVersion: v1
kind: Service
metadata:
  name: {{ self.datadog__fullname() }}
  labels:
    app: {{ self.datadog__fullname() }}
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    release: "{{ Release.Name }}"
spec:
  type: {{ Values.serviceType }}
  selector:
    app: {{ self.datadog__fullname() }}
  ports:
  - port: 8125
    name: dogstatsdport
    protocol: UDP
  {%- if Values.datadog.apmEnabled %}
  - port: 8126
    name: traceport
    protocol: TCP
  {%- endif %}
{%- endif %}
