{%- if (Values.auth.enabled) and ( not  Values.auth.existingSecret) -%}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ self.mailhog__name() }}
    chart: {{ Chart.Name }}-{{ Chart.Version }}
    heritage: {{ Release.Service }}
    release: {{ Release.Name }}
  name: {{ self.mailhog__authFileSecret() }}
type: Opaque
data:
  {{ Values.auth.fileName }}: {{ Values.auth.fileContents | b64enc() }}
{%- endif -%}
