apiVersion: v1
kind: Service
metadata:
{%- if Values.service.annotations %}
  annotations:
{{ toYaml(Values.service.annotations) | indent(4) }}
{%- endif %}
  labels:
    app: {{ self.mailhog__name() }}
    chart: {{ Chart.Name }}-{{ Chart.Version }}
    heritage: {{ Release.Service }}
    release: {{ Release.Name }}
  name: {{ self.mailhog__fullname() }}
spec:
  type: "{{ Values.service.type }}"
  clusterIP: "{{ Values.service.clusterIP }}"
{%- if Values.service.externalIPs %}
  externalIPs:
{{ toYaml(Values.service.externalIPs) | indent(4) }}
{%- endif %}
{%- if Values.service.loadBalancerIP %}
  loadBalancerIP: "{{ Values.service.loadBalancerIP }}"
{%- endif %}
{%- if Values.service.loadBalancerSourceRanges %}
  loadBalancerSourceRanges:
{{ toYaml(Values.service.loadBalancerSourceRanges) | indent(4) }}
{%- endif %}
  ports:
    - name: http
      port: {{ Values.service.port.http }}
      protocol: TCP
      targetPort: http
      {%- if ((Values.service.type=="NodePort") and ( not  ( empty  Values.service.nodePort.http))) %}
      nodePort: {{ Values.service.nodePort.http }}
      {%- endif %}
    - name: smtp
      port: {{ Values.service.port.smtp }}
      protocol: TCP
      targetPort: smtp
      {%- if ((Values.service.type=="NodePort") and ( not  ( empty  Values.service.nodePort.smtp))) %}
      nodePort: {{ Values.service.nodePort.smtp }}
      {%- endif %}
  selector:
    app: {{ self.mailhog__name() }}
    release: {{ Release.Name }}
