{%- if (Values.ingress.tls.enabled) and ( not  Values.ingress.tls.existingSecret) -%}
apiVersion: v1
kind: Secret
metadata:
{%- if Values.ingress.tls.secretAnnotations %}
  annotations:
{{ toYaml(Values.ingress.tls.secretAnnotations) | indent(4) }}
{%- endif %}
  labels:
    app: {{ self.mailhog__name() }}
    chart: {{ Chart.Name }}-{{ Chart.Version }}
    heritage: {{ Release.Service }}
    release: {{ Release.Name }}
  name: {{ self.mailhog__tlsSecret() }}
type: Opaque
data:
{{ toYaml(Values.ingress.tls.secretContents) | indent(2) }}
{%- endif -%}
