apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ self.jasperreports__fullname() }}
  labels:
    app: {{ self.jasperreports__fullname() }}
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    release: "{{ Release.Name }}"
    heritage: "{{ Release.Service }}"
spec:
  template:
    metadata:
      labels:
        app: {{ self.jasperreports__fullname() }}
    spec:
      containers:
      - name: {{ self.jasperreports__fullname() }}
        image: "{{ Values.image }}"
        imagePullPolicy: {{ Values.imagePullPolicy | default("", true) | quote() }}
        env:
        - name: MARIADB_HOST
          value: {{ self.jasperreports__mariadb__fullname() }}
        - name: MARIADB_PORT_NUMBER
          value: "3306"
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ self.jasperreports__mariadb__fullname() }}
              key: mariadb-root-password
        - name: JASPERREPORTS_USERNAME
          value: {{ Values.jasperreportsUsername | default("", true) | quote() }}
        - name: JASPERREPORTS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ self.jasperreports__fullname() }}
              key: jasperreports-password
        - name: JASPERREPORTS_EMAIL
          value: {{ Values.jasperreportsEmail | default("", true) | quote() }}
        - name: SMTP_HOST
          value: {{ Values.smtpHost | default("", true) | quote() }}
        - name: SMTP_PORT
          value: {{ Values.smtpPort | default("", true) | quote() }}
        - name: SMTP_EMAIL
          value: {{ Values.smtpEmail | default("", true) | quote() }}
        - name: SMTP_USER
          value: {{ Values.smtpUser | default("", true) | quote() }}
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ self.jasperreports__fullname() }}
              key: smtp-password
        - name: SMTP_PROTOCOL
          value: {{ Values.smtpProtocol | default("", true) | quote() }}
        ports:
        - name: http
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /jasperserver/login.html
            port: http
          initialDelaySeconds: 300
          timeoutSeconds: 5
          failureThreshold: 6
        readinessProbe:
          httpGet:
            path: /jasperserver/login.html
            port: http
          initialDelaySeconds: 30
          timeoutSeconds: 3
          periodSeconds: 5
        resources:
{{ toYaml(Values.resources) | indent(10) }}
        volumeMounts:
        - name: jasperreports-data
          mountPath: /bitnami/jasperreports
      volumes:
      - name: jasperreports-data
      {%- if Values.persistence.enabled %}
        persistentVolumeClaim:
          claimName: {{ self.jasperreports__fullname() }}
      {%- else %}
        emptyDir: {}
      {%- endif %}
