{%- if Values.persistence.enabled -%}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ self.jasperreports__fullname() }}
  labels:
    app: {{ self.jasperreports__fullname() }}
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    release: "{{ Release.Name }}"
    heritage: "{{ Release.Service }}"
  annotations:
  {%- if Values.persistence.storageClass %}
    volume.beta.kubernetes.io/storage-class: {{ Values.persistence.storageClass | quote() }}
  {%- else %}
    volume.alpha.kubernetes.io/storage-class: default
  {%- endif %}
spec:
  accessModes:
    - {{ Values.persistence.accessMode | quote() }}
  resources:
    requests:
      storage: {{ Values.persistence.size | quote() }}
{%- endif -%}
