{%- if (Values.persistence.enabled) and ( not  Values.persistence.useExisting) %}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{%- if  not  ( empty  Values.persistence.name) %}{{ Values.persistence.name }}{%- else %}{{ self.influxdb__fullname() }}{%- endif %}"
  labels:
    app: "{%- if  not  ( empty  Values.persistence.name) %}{{ Values.persistence.name }}{%- else %}{{ self.influxdb__fullname() }}{%- endif %}"
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    release: "{{ Release.Name }}"
    heritage: "{{ Release.Service }}"
spec:
  accessModes:
    - {{ Values.persistence.accessMode | quote() }}
  resources:
    requests:
      storage: {{ Values.persistence.size | quote() }}
{%- if Values.persistence.storageClass %}
{%- if ("-"==Values.persistence.storageClass) %}
  storageClassName: ""
{%- else %}
  storageClassName: "{{ Values.persistence.storageClass }}"
{%- endif %}
{%- endif %}
{%- endif %}
