{%- if Values.setDefaultUser.enabled -%}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ self.influxdb__fullname() }}
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    heritage: "{{ Release.Service }}"
    release: "{{ Release.Name }}"
  name: {{ self.influxdb__fullname() }}-auth
data:
  {%- if Values.setDefaultUser.user.password %}
  influxdb-password:  {{ Values.setDefaultUser.user.password | b64enc() | quote() }}
  {%- else %}
  influxdb-password: {{ randAscii 10 | b64enc() | quote() }}
  {%- endif %}
  influxdb-user: {{ Values.setDefaultUser.user.username | b64enc() | quote() }}
{%- endif -%}
