{%- if Values.registryCreds.gcrServiceAccountKey %}
apiVersion: v1
kind: Secret
metadata:
  name: {{ self.buildkite__fullname() }}-gcr
  labels:
    app: {{ self.buildkite__name() }}
    chart: {{ Chart.Name }}-{{ Chart.Version | replace("+","_") }}
    release: {{ Release.Name }}
    heritage: {{ Release.Service }}
type: Opaque
data:
  service-account-key.json: |-
    {{ Values.registryCreds.gcrServiceAccountKey }}
{%- endif %}
