{%- if Values.registryCreds.dockerConfig %}
apiVersion: v1
kind: Secret
metadata:
  name: {{ self.buildkite__fullname() }}-registry
  labels:
    app: {{ self.buildkite__name() }}
    chart: {{ Chart.Name }}-{{ Chart.Version | replace("+","_") }}
    release: {{ Release.Name }}
    heritage: {{ Release.Service }}
type: Opaque
data:
  .dockerconfigjson: |-
    {{ Values.registryCreds.dockerConfig }}
{%- endif %}
