apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ self.buildkite__fullname() }}
  labels:
    app: {{ self.buildkite__name() }}
    chart: {{ Chart.Name }}-{{ Chart.Version | replace("+","_") }}
    release: {{ Release.Name }}
    heritage: {{ Release.Service }}
