apiVersion: v1
kind: Service
metadata:
  name: {{ self.dask-distributed__jupyter-fullname() }}
  labels:
    app: {{ self.dask-distributed__name() }}
    heritage: {{ Release.Service | quote() }}
    release: {{ Release.Name | quote() }}
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    component: "{{ Release.Name }}-{{ Values.jupyter.component }}"
spec:
  ports:
    - port: {{ Values.jupyter.servicePort }}
      targetPort: {{ Values.jupyter.containerPort }}
  selector:
    app: {{ self.dask-distributed__name() }}
    release: {{ Release.Name | quote() }}
    component: "{{ Release.Name }}-{{ Values.jupyter.component }}"
  type: {{ Values.jupyter.serviceType }}
