apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ self.dask-distributed__jupyter-fullname() }}-config
  labels:
    app: {{ self.dask-distributed__name() }}
    heritage: {{ Release.Service | quote() }}
    release: {{ Release.Name | quote() }}
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    component: "{{ Release.Name }}-{{ Values.jupyter.component }}"
data:
  jupyter_notebook_config.py: |
    c = get_config()
    c.NotebookApp.password = '{{ Values.jupyter.password }}'
