apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ self.dask-distributed__jupyter-fullname() }}
  labels:
    app: {{ self.dask-distributed__name() }}
    heritage: {{ Release.Service | quote() }}
    release: {{ Release.Name | quote() }}
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    component: "{{ Release.Name }}-{{ Values.jupyter.component }}"
spec:
  replicas: {{ Values.jupyter.replicas }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ self.dask-distributed__name() }}
        release: {{ Release.Name | quote() }}
        component: "{{ Release.Name }}-{{ Values.jupyter.component }}"
    spec:
      containers:
        - name: {{ self.dask-distributed__jupyter-fullname() }}
          image: "{{ Values.jupyter.image }}:{{ Values.jupyter.imageTag }}"
          ports:
            - containerPort: {{ Values.jupyter.containerPort }}
          resources:
{{ toYaml(Values.jupyter.resources) | indent(12) }}
          volumeMounts:
          - name: config-volume
            mountPath: /home/jovyan/.jupyter
      volumes:
      - name: config-volume
        configMap:
          name: {{ self.dask-distributed__jupyter-fullname() }}-config
