apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ self.dask-distributed__worker-fullname() }}
  labels:
    app: {{ self.dask-distributed__name() }}
    heritage: {{ Release.Service | quote() }}
    release: {{ Release.Name | quote() }}
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    component: "{{ Release.Name }}-{{ Values.worker.component }}"
spec:
  replicas: {{ Values.worker.replicas }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ self.dask-distributed__name() }}
        release: {{ Release.Name | quote() }}
        component: "{{ Release.Name }}-{{ Values.worker.component }}"
    spec:
      containers:
        - name: {{ self.dask-distributed__worker-fullname() }}
          image: "{{ Values.worker.image }}:{{ Values.worker.imageTag }}"
          command: ["dask-worker", "{{ self.dask-distributed__scheduler-fullname() }}:{{ Values.scheduler.servicePort }}"]
          ports:
            - containerPort: {{ Values.worker.containerPort }}
          resources:
{{ toYaml(Values.worker.resources) | indent(12) }}
