apiVersion: v1
kind: Service
metadata:
  name: {{ self.dask-distributed__scheduler-fullname() }}
  labels:
    app: {{ self.dask-distributed__name() }}
    heritage: {{ Release.Service | quote() }}
    release: {{ Release.Name | quote() }}
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    component: "{{ Release.Name }}-{{ Values.scheduler.component }}"
spec:
  ports:
    - name: {{ self.dask-distributed__scheduler-fullname() }}
      port: {{ Values.scheduler.servicePort }}
      targetPort: {{ Values.scheduler.containerPort }}
    - name: {{ self.dask-distributed__webui-fullname() }}
      port: {{ Values.webUI.servicePort }}
      targetPort: {{ Values.webUI.containerPort }}
  selector:
    app: {{ self.dask-distributed__name() }}
    release: {{ Release.Name | quote() }}
    component: "{{ Release.Name }}-{{ Values.scheduler.component }}"
  type: {{ Values.scheduler.serviceType }}
