



---




---

apiVersion: v1
kind: Secret
metadata:
  name: test-buildkite
  labels:
    app: buildkite
    chart: buildkite-0.2.0
    release: test
    heritage: buildkite
type: Opaque
data:
  agent-token: 


---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-buildkite
  labels:
    app: buildkite
    chart: buildkite-0.2.0
    release: test
    heritage: buildkite


---

