apiVersion: v1
description: Agent for Buildkite
name: buildkite
version: 0.2.0
appVersion: 3.0
icon: https://github.com/buildkite/media/blob/master/marks/Buildkite---Mark---colour.png.png
keywords:
- kubernetes deployment
- helm release
- continuous deployment
- continuous integration
home: https://buildkite.com
sources:
- https://github.com/buildkite/agent
maintainers:
- name: rimusz
  email: rmocius@gmail.com
