apiVersion: v1
kind: Secret
metadata:
  name: {{ self.fullname() }}
  labels:
    app: {{ self.name() }}
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    release: "{{ Release.Name }}"
    heritage: "{{ Release.Service }}"
type: Opaque
data:
  {%- if Values.sugarcrmPassword %}
  sugarcrm-password: {{ Values.sugarcrmPassword | b64enc() | quote() }}
  {%- else %}
  sugarcrm-password: {{ randAlphaNum(10) | b64enc() | quote() }}
  {%- endif %}
  sugarcrm-smtp-password: {{ Values.sugarcrmSmtpPassword | default("", true) | b64enc() | quote() }}
