apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ "%s-%s" | format(Release.Name,Values.name) }}
  labels:
    app: {{ "%s-%s" | format(Release.Name,Values.name) }}
    chart: {{ Chart.Name }}-{{ Chart.Version }}
    release: {{ Release.Name }}
    heritage: {{ Release.Service }}
spec:
  replicas: {{ Values.replicas }}
  template:
    metadata:
      labels:
        app: {{ "%s-%s" | format(Release.Name,Values.name) }}
        chart: {{ Chart.Name }}-{{ Chart.Version }}
        release: {{ Release.Name }}
        heritage: {{ Release.Service }}
    spec:
      containers:
      - name: {{ Values.name }}
        image: {{ Values.image }}:{{ Values.imageTag }}
        args:
        - --in-cluster
        - --interval={{ Values.interval }}
        - --labels={{ Values.labels }}
        - --annotations={{ Values.annotations }}
        - --namespaces={{ Values.namespaces }}
        {%- if  not  Values.dryRun %}
        - --no-dry-run
        {%- endif %}
        resources:
          requests:
            cpu: {{ Values.resources.cpu }}
            memory: {{ Values.resources.memory }}
          limits:
            cpu: {{ Values.resources.cpu }}
            memory: {{ Values.resources.memory }}
