


---


kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-mysql
  labels:
    app: test-mysql
    chart: "mysql-0.3.0"
    release: "test"
    heritage: "mysql"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "8Gi"


---

apiVersion: v1
kind: Secret
metadata:
  name: test-mysql
  labels:
    app: test-mysql
    chart: "mysql-0.3.0"
    release: "test"
    heritage: "mysql"
type: Opaque
data:
  mysql-root-password: "CnZubnl4am1vdXgK"
  mysql-password: "CmR6a213ZHluYWYK"


---

apiVersion: v1
kind: Service
metadata:
  name: test-mysql
  labels:
    app: test-mysql
    chart: "mysql-0.3.0"
    release: "test"
    heritage: "mysql"
spec:
  ports:
  - name: mysql
    port: 3306
    targetPort: mysql
  selector:
    app: test-mysql


---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test-mysql
  labels:
    app: test-mysql
    chart: "mysql-0.3.0"
    release: "test"
    heritage: "mysql"
spec:
  template:
    metadata:
      labels:
        app: test-mysql
    spec:
      initContainers:
      - name: "remove-lost-found"
        image: "busybox:1.25.0"
        imagePullPolicy: "IfNotPresent"
        command:  ["rm", "-fr", "/var/lib/mysql/lost+found"]
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
      containers:
      - name: test-mysql
        image: "mysql:5.7.14"
        imagePullPolicy: "IfNotPresent"
        resources:
          requests: {cpu: 100m, memory: 256Mi}
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: test-mysql
              key: mysql-root-password
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: test-mysql
              key: mysql-password
        - name: MYSQL_USER
          value: ""
        - name: MYSQL_DATABASE
          value: ""
        ports:
        - name: mysql
          containerPort: 3306
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}"
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}"
          initialDelaySeconds: 5
          timeoutSeconds: 1
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: test-mysql