apiVersion: v1
kind: Service
metadata:
  name: {{ self.sensu__fullname() }}
  labels:
    heritage: {{ Release.Service | quote() }}
    release: {{ Release.Name | quote() }}
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
  {%- if Values.deis.routable %}
    router.deis.io/routable: "true"
  annotations:
    router.deis.io/domains: {{ Values.deis.domains | quote() }}
  {%- endif %}
spec:
  type: {{ Values.serviceType }}
  ports:
  - port: {{ Values.httpPort }}
    targetPort: 4567
  selector:
    app: {{ self.sensu__fullname() }}
