
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-minecraft-datadir
  labels:
    app: test-minecraft
    chart: "minecraft-0.2.0"
    release: "test"
    heritage: "minecraft"
  annotations:
    volume.alpha.kubernetes.io/storage-class: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "1Gi"

---

apiVersion: v1
kind: Secret
metadata:
  name: test-minecraft
  labels:
    app: test-minecraft
    chart: "minecraft-0.2.0"
    release: "test"
    heritage: "minecraft"
type: Opaque
data:
  rcon-password: "Q0hBTkdFTUUh"


---

apiVersion: v1
kind: Service
metadata:
  name: test-minecraft
  labels:
    app: test-minecraft
    chart: "minecraft-0.2.0"
    release: "test"
    heritage: "minecraft"
spec:
  type: LoadBalancer
  ports:
  - name: minecraft
    port: 25565
    targetPort: minecraft
    protocol: TCP
  selector:
    app: test-minecraft


---




---

