{%- if Values.acme.enabled and Values.acme.persistence.enabled %}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ self.fullname() }}-acme
  labels:
    app: {{ self.fullname() }}
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    release: "{{ Release.Name }}"
    heritage: "{{ Release.Service }}"
spec:
  accessModes:
    - {{ Values.acme.persistence.accessMode | quote() }}
  resources:
    requests:
      storage: {{ Values.acme.persistence.size | quote() }}
{%- if Values.acme.persistence.storageClass %}
{%- if ("-"==Values.acme.persistence.storageClass) %}
  storageClassName: ""
{%- else %}
  storageClassName: "{{ Values.acme.persistence.storageClass }}"
{%- endif %}
{%- endif %}
{%- endif %}
