apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ self.fullname() }}
  labels:
    app: {{ self.fullname() }}
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    release: "{{ Release.Name }}"
    heritage: "{{ Release.Service }}"
data:
  traefik.toml: |
    # traefik.toml
    logLevel = "INFO"
    {%- if Values.debug.enabled %}
    debug = true
    {%- endif %}
    {%- if Values.ssl.enabled %}
    defaultEntryPoints = ["http","https"]
    {%- else %}
    defaultEntryPoints = ["http"]
    {%- endif %}
    [entryPoints]
      [entryPoints.http]
      address = ":80"
      compress = {{ Values.gzip.enabled }}
        {%- if Values.ssl.enabled and Values.ssl.enforced %}
        [entryPoints.http.redirect]
          entryPoint = "https"
        {%- endif %}
      {%- if Values.ssl.enabled %}
      [entryPoints.https]
      address = ":443"
      compress = {{ Values.gzip.enabled }}
        [entryPoints.https.tls]
          [[entryPoints.https.tls.certificates]]
          CertFile = "/ssl/tls.crt"
          KeyFile = "/ssl/tls.key"
      {%- endif %}
    [kubernetes]
    {%- if Values.kubernetes %}
      {%- if Values.kubernetes.namespaces %}
    namespaces = [
        {%- for idx, element in Values.kubernetes.namespaces.iteritems() %}
            {%- if idx %}, {%- endif %}
            {{ element | quote() }}
        {%- endfor -%}
        ]
      {%- endif %}
      {%- if Values.kubernetes.labelSelector %}
    labelselector = {{ Values.kubernetes.labelSelector | quote() }}
      {%- endif %}
    {%- endif %}
    {%- if Values.accessLogs.enabled %}
    [accessLogs]
    {%- if Values.accessLogs.filePath %}
    filePath = "{{ Values.accessLogs.filePath }}"
    {%- endif %}
    format = "{{ Values.accessLogs.format }}"
    {%- endif %}
    {%- if Values.acme.enabled %}
    [acme]
    email = "{{ Values.acme.email }}"
    storage = "/acme/acme.json"
    entryPoint = "https"
    onHostRule = true
    {%- if Values.acme.staging %}
    caServer = "https://acme-staging.api.letsencrypt.org/directory"
    {%- endif %}
    {%- endif %}
    {%- if Values.dashboard.enabled %}
    [web]
    address = ":8080"
      {%- if Values.dashboard.auth %}
      {%- if Values.dashboard.auth.basic %}
      [web.auth.basic]
        users = [{%- for key, value in Values.dashboard.auth.basic.iteritems() %}"{{ key }}:{{ value }}",{%- endfor %}]
      {%- endif %}
      {%- endif %}
      {%- if Values.dashboard.statistics %}
      {%- if Values.dashboard.statistics.recentErrors %}
      [web.statistics]
        RecentErrors = {{ Values.dashboard.statistics.recentErrors }}
      {%- endif %}
      {%- endif %}
    {%- endif %}
    {%- if Values.metrics.prometheus.enabled %}
    [web.metrics.prometheus]
      Buckets = {{ Values.metrics.prometheus.buckets }}
    {%- endif %}
    {%- if Values.metrics.datadog.enabled %}
    [web.metrics.datadog]
      Address = {{ Values.metrics.datadog.address }}
      PushInterval = "{{ Values.metrics.datadog.pushInterval }}"
    {%- endif %}
    {%- if Values.metrics.statsd.enabled %}
    [web.metrics.statsd]
      Address = {{ Values.metrics.statsd.address }}
      PushInterval = "{{ Values.metrics.statsd.pushInterval }}"
    {%- endif %}
