{%- if Values.rbac.enabled %}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ self.fullname() }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ self.fullname() }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ self.fullname() }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ self.fullname() }}
subjects:
- kind: ServiceAccount
  name: {{ self.fullname() }}
  namespace: {{ Release.Namespace }}
{%- endif %}
