apiVersion: v1
kind: Service
metadata:
  name: {{ self.fullname() }}
  labels:
    app: {{ self.fullname() }}
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    release: "{{ Release.Name }}"
    heritage: "{{ Release.Service }}"
  {%- if Values.service %}
  {%- for key, value in Values.service.labels.iteritems() %}
    {{ key }}: {{ value | quote() }}
  {%- endfor %}
  {%- endif %}
  annotations:
  {%- if Values.service %}
  {%- for key, value in Values.service.annotations.iteritems() %}
    {{ key }}: {{ value | quote() }}
  {%- endfor %}
  {%- endif %}
spec:
  type: {{ Values.serviceType }}
  {%- if Values.loadBalancerIP %}
  loadBalancerIP: {{ Values.loadBalancerIP }}
  {%- endif %}
  {%- if Values.loadBalancerSourceRanges %}
  loadBalancerSourceRanges:
    {%- for cidr in Values.loadBalancerSourceRanges %}
    - {{ cidr }}
    {%- endfor %}
  {%- endif %}
  selector:
    app: {{ self.fullname() }}
  ports:
  - port: 80
    name: http
  - port: 443
    name: https
    {%- if  not  Values.ssl.enabled %}
    targetPort: 80
    {%- endif %}
  {%- if Values.metrics.prometheus.enabled or Values.metrics.datadog.enabled or Values.metrics.statsd.enabled %}
  - port: 8080
    name: metrics
  {%- endif %}
