apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ self.locust__master() }}
  labels:
    app: {{ self.locust__fullname() }}
    heritage: {{ Release.Service | quote() }}
    release: {{ Release.Name | quote() }}
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    component: master
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ Values.master.maxSurge | default(1, true) }}
      maxUnavailable: {{ Values.master.maxUnavailable | default(1, true) }}
  template:
    metadata:
      labels:
        release: {{ Release.Name | quote() }}
        app: {{ self.locust__fullname() }}
        component: "master"
    spec:
      containers:
      - name: locust
        image: "{{ Values.image.repository }}:{{ Values.image.tag }}"
        imagePullPolicy: {{ Values.image.pullPolicy }}
        resources:
{{ toYaml(Values.worker.resources) | indent(10) }}
        env:
        {%- for key, value in Values.master.config.iteritems() %}
        - name: {{ key | upper() | replace("-","_") }}
          value: {{ value | quote() }}
        {%- endfor %}
        - name: LOCUST_MODE
          value: "master"
        - name: LOCUST_SCRIPT
          value: {{ Values.worker.config | index("locust-script")| quote() }}
        ports:
        - containerPort: {{ Values.service.internalPort }}
          name: loc-master-web
          protocol: TCP
        - containerPort: 5557
          name: loc-master-p1
          protocol: TCP
        - containerPort: 5558
          name: loc-master-p2
          protocol: TCP
        volumeMounts:
          - name: locust-tasks
            mountPath: /locust-tasks/
        livenessProbe:
          periodSeconds: 30
          httpGet:
            path: /
            port: {{ Values.service.internalPort }}
        readinessProbe:
          periodSeconds: 30
          httpGet:
            path: /
            port: {{ Values.service.internalPort }}
      volumes:
      - name: "locust-tasks"
        configMap:
          name: {{ self.locust__worker-configmap() }}
      restartPolicy: Always
