apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ self.locust__worker-configmap() }}
  labels:
    heritage: {{ Release.Service | quote() }}
    release: {{ Release.Name | quote() }}
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    app: {{ self.locust__fullname() }}
data:
{{ (.Files.Glob "tasks/*").AsConfig | indent(2) }}
