{%- if Values.nginx.persistence.enabled %}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ self.artifactory__nginx__fullname() }}
  labels:
    app: {{ self.artifactory__name() }}
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    release: "{{ Release.Name }}"
    heritage: "{{ Release.Service }}"
spec:
  accessModes:
    - {{ Values.nginx.persistence.accessMode | quote() }}
  resources:
    requests:
      storage: {{ Values.nginx.persistence.size | quote() }}
{%- if Values.nginx.persistence.storageClass %}
{%- if ("-"==Values.nginx.persistence.storageClass) %}
  storageClassName: ""
{%- else %}
  storageClassName: "{{ Values.nginx.persistence.storageClass }}"
{%- endif %}
{%- endif %}
{%- endif %}
