apiVersion: v1
kind: Service
metadata:
  name: {{ self.artifactory__database__name() }}
  labels:
    app: {{ self.artifactory__name() }}
    chart: {{ Chart.Name }}-{{ Chart.Version }}
    component: "{{ Values.database.name }}"
    heritage: {{ Release.Service }}
    release: {{ Release.Name }}
spec:
  type: {{ Values.database.service.type }}
  ports:
  - port: {{ Values.database.externalPort }}
    targetPort: {{ Values.database.internalPort }}
    protocol: TCP
    name: {{ Release.Name }}
  selector:
    app: {{ self.artifactory__name() }}
    component: "{{ Values.database.name }}"
    release: {{ Release.Name }}