
apiVersion: v1
kind: Service
metadata:
  name: test-sapho
  labels:
    chart: "sapho-0.2.0"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: sapho
  selector:
    app: test-sapho


---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test-sapho
  labels:
    app: test-sapho
    chart: "sapho-0.2.0"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: test-sapho
    spec:
      containers:
      - name: test-sapho
        image: "sapho/ops-docker-tomcat:8-jre8"
        imagePullPolicy: ""
        env:
        - name: SAPHO_DB_HOSTNAME
          value: test-mysql
        - name: SAPHO_DB_PORT
          value: "3306"
        - name: SAPHO_DB_TYPE
          value: mysql
        - name: SAPHO_DB_USERNAME
          value: root
        - name: SAPHO_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: test-mysql
              key: mysql-root-password
        ports:
        - name: http
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 180
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          timeoutSeconds: 5
        resources:
            requests: {cpu: 250m, memory: 2048Mi}