apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ self.dokuwiki__fullname() }}
  labels:
    app: {{ self.dokuwiki__fullname() }}
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    release: "{{ Release.Name }}"
    heritage: "{{ Release.Service }}"
spec:
  template:
    metadata:
      labels:
        app: {{ self.dokuwiki__fullname() }}
    spec:
      containers:
      - name: {{ self.dokuwiki__fullname() }}
        image: "{{ Values.image }}"
        imagePullPolicy: {{ Values.imagePullPolicy | default("", true) | quote() }}
        env:
        - name: DOKUWIKI_USERNAME
          value: {{ Values.dokuwikiUsername | default("", true) | quote() }}
        - name: DOKUWIKI_FULL_NAME
          value: {{ Values.dokuwikiFullName | default("", true) | quote() }}
        - name: DOKUWIKI_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ self.dokuwiki__fullname() }}
              key: dokuwiki-password
        - name: DOKUWIKI_EMAIL
          value: {{ Values.dokuwikiEmail | default("", true) | quote() }}
        - name: DOKUWIKI_WIKI_NAME
          value: {{ Values.dokuwikiWikiName | default("", true) | quote() }}
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        livenessProbe:
          httpGet:
            path: /doku.php
            port: http
          initialDelaySeconds: 120
          timeoutSeconds: 5
          failureThreshold: 6
        readinessProbe:
          httpGet:
            path: /doku.php
            port: http
          initialDelaySeconds: 30
          timeoutSeconds: 3
          periodSeconds: 5
        resources:
{{ toYaml(Values.resources) | indent(10) }}
        volumeMounts:
        - name: dokuwiki-data
          mountPath: /bitnami/dokuwiki
        - name: apache-data
          mountPath: /bitnami/apache
      volumes:
      - name: dokuwiki-data
      {%- if Values.persistence.enabled %}
        persistentVolumeClaim:
          claimName: {{ self.dokuwiki__fullname() }}-dokuwiki
      {%- else %}
        emptyDir: {}
      {%- endif %}
      - name: apache-data
      {%- if Values.persistence.enabled %}
        persistentVolumeClaim:
          claimName: {{ self.dokuwiki__fullname() }}-apache
      {%- else %}
        emptyDir: {}
      {%- endif %}
