apiVersion: v1
kind: Service
metadata:
  name: {{ self.dokuwiki__fullname() }}
  labels:
    app: {{ self.dokuwiki__fullname() }}
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    release: "{{ Release.Name }}"
    heritage: "{{ Release.Service }}"
spec:
  type: {{ Values.serviceType }}
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: https
    port: 443
    targetPort: https
  selector:
    app: {{ self.dokuwiki__fullname() }}
