apiVersion: v1
kind: Service
metadata:
  name: "{{ self.rethinkdb__fullname() }}-admin"
  labels:
    app: "{{ self.rethinkdb__name() }}-admin"
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    heritage: {{ Release.Service | quote() }}
    release: {{ Release.Name | quote() }}
spec:
  clusterIP: None
  ports:
    - port: {{ Values.ports.admin }}
      targetPort: admin
  selector:
    app: "{{ self.rethinkdb__name() }}-proxy"
    release: {{ Release.Name | quote() }}
