apiVersion: v1
kind: Service
metadata:
  name: "{{ self.rethinkdb__fullname() }}-cluster"
  labels:
    app: "{{ self.rethinkdb__name() }}-cluster"
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    heritage: {{ Release.Service | quote() }}
    release: {{ Release.Name | quote() }}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  {%- if Values.cluster.service.annotations %}
{{ toYaml(Values.cluster.service.annotations) | indent(4) }}
  {%- endif %}
spec:
  clusterIP: None
  ports:
    - port: {{ Values.ports.cluster }}
      targetPort: cluster
  selector:
    app: "{{ self.rethinkdb__name() }}-cluster"
    release: {{ Release.Name | quote() }}
