{%- if Values.cluster.storageClass.enabled %}
apiVersion: {%- if  Capabilities.APIVersions.Has  "storage.k8s.io/v1" -%}
  storage.k8s.io/v1
{%- else -%}
  storage.k8s.io/v1beta1
{%- endif %}
kind: StorageClass
metadata:
  labels:
    app: "{{ self.rethinkdb__name() }}-cluster"
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    heritage: {{ Release.Service | quote() }}
    release: {{ Release.Name | quote() }}
  name: {{ self.rethinkdb__fullname() }}
provisioner: {{ Values.cluster.storageClass.provisioner }}
parameters:
{%- for key, value in Values.cluster.storageClass.parameters.iteritems() %}
  {{ key }}: {{ value }}
{%- endfor %}
{%- endif %}
