apiVersion: v1
kind: Secret
metadata:
  name: {{ self.gcloud-sqlproxy__fullname() }}
  labels:
    app: {{ self.gcloud-sqlproxy__fullname() }}
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    release: "{{ Release.Name }}"
    heritage: "{{ Release.Service }}"
type: Opaque
data:
  credentials.json: |-
    {{ Values.serviceAccountKey }}
