apiVersion: v1
kind: Service
metadata:
  name: {{ self.gcloud-sqlproxy__fullname() }}
  labels:
    app: {{ self.gcloud-sqlproxy__fullname() }}
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    release: "{{ Release.Name }}"
    heritage: "{{ Release.Service }}"
spec:
  ports:
  - name: sqlproxy
    protocol: TCP
    port: {{ Values.cloudsql.port }}
    targetPort: sqlproxy
  selector:
    app: {{ self.gcloud-sqlproxy__fullname() }}
