
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-datadog-autoconf
  labels:
    app: test-datadog-autoconf
    chart: "datadog-0.8.0"
    release: "test"
    heritage: "datadog"
data:
  {kubernetes_state.yaml: "docker_images:\n  - kube-state-metrics\ninit_config:\ninstances:\n\
      \  - kube_state_url: http://%%host%%:%%port%%/metrics"}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: test-datadog-checksd
  labels:
    app: test-datadog-checksd
    chart: "datadog-0.8.0"
    release: "test"
    heritage: "datadog"
data:

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: test-datadog-confd
  labels:
    app: test-datadog-confd
    chart: "datadog-0.8.0"
    release: "test"
    heritage: "datadog"
data:

---




---

apiVersion: v1
kind: Secret
metadata:
  name: test-datadog
  labels:
    app: test-datadog
    chart: "datadog-0.8.0"
    release: "test"
    heritage: "datadog"
type: Opaque
data:
  api-key: "TUlTU0lORw=="


---




---

