apiVersion: v1
kind: Secret
metadata:
  name: {{ self.mongodb__fullname() }}
  labels:
    app: {{ self.mongodb__fullname() }}
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    release: "{{ Release.Name }}"
    heritage: "{{ Release.Service }}"
type: Opaque
data:
  mongodb-root-password: {{ Values.mongodbRootPassword | default("", true) | b64enc() | quote() }}
  mongodb-password: {{ Values.mongodbPassword | default("", true) | b64enc() | quote() }}
