apiVersion: v1
kind: Service
metadata:
  name: {{ self.coredns__fullname() }}
  labels:
    heritage: {{ Release.Service | quote() }}
    release: {{ Release.Name | quote() }}
    chart: "{{ Chart.Name }}-{{ Chart.Version | replace("+","_") }}"
    {%- if Values.isClusterService %}
    k8s-app: {{ Chart.Name | quote() }}
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "CoreDNS"
    {%- else %}
    app: {{ self.coredns__fullname() }}
    {%- endif %}
  annotations:
    {%- if Values.middleware.prometheus.enabled %}
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ Values.middleware.prometheus.port | quote() }}
    {%- endif %}
spec:
  selector:
  {%- if Values.isClusterService %}
    k8s-app: {{ Chart.Name | quote() }}
  {%- else %}
    app: {{ self.coredns__fullname() }}
  {%- endif %}
  {%- if Values.isClusterService %}
  clusterIP: {{ Values.middleware.kubernetes.clusterIP }}
  {%- endif %}
  ports:
  {%- if (Values.serviceProtocol=="UDPNTCP") or (Values.serviceProtocol=="UDP") %}
  - name: dns
    port: 53
    protocol: UDP
  {%- endif %}
  {%- if (Values.serviceProtocol=="UDPNTCP") or (Values.serviceProtocol=="TCP") %}
  - name: dns-tcp
    port: 53
    protocol: TCP
  {%- endif %}
  {%- if Values.middleware.prometheus.enabled %}
  - name: metrics
    port: {{ Values.middleware.prometheus.port }}
    protocol: TCP
  {%- endif %}
  type: {{ Values.serviceType | default("ClusterIP", true) }}
