apiVersion: v1
kind: Secret
metadata:
  name: {{ self.concourse__concourse__fullname() }}
  labels:
    app: {{ self.concourse__concourse__fullname() }}
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    release: "{{ Release.Name }}"
    heritage: "{{ Release.Service }}"
type: Opaque
data:
  {%- if Values.postgresql.enabled %}
  postgresql-user: {{ Values.postgresql.postgresUser | b64enc() | quote() }}
  {%- else %}
  postgresql-uri: {{ Values.postgresql.uri | b64enc() | quote() }}
  {%- endif %}
  basic-auth-username: {{ Values.concourse.username | b64enc() | quote() }}
  basic-auth-password: {{ Values.concourse.password | b64enc() | quote() }}
  host-key: {{ Values.concourse.hostKey | b64enc() | quote() }}
  host-key-pub: {{ Values.concourse.hostKeyPub | b64enc() | quote() }}
  session-signing-key: {{ Values.concourse.sessionSigningKey | b64enc() | quote() }}
  worker-key: {{ Values.concourse.workerKey | b64enc() | quote() }}
  worker-key-pub: {{ Values.concourse.workerKeyPub | b64enc() | quote() }}
  github-auth-client-id: {{ Values.concourse.githubAuthClientId | default("", true) | b64enc() | quote() }}
  github-auth-client-secret: {{ Values.concourse.githubAuthClientSecret | default("", true) | b64enc() | quote() }}
  gitlab-auth-client-id: {{ Values.concourse.gitlabAuthClientId | default("", true) | b64enc() | quote() }}
  gitlab-auth-client-secret: {{ Values.concourse.gitlabAuthClientSecret | default("", true) | b64enc() | quote() }}
  generic-oauth-client-id: {{ Values.concourse.genericOauthClientId | default("", true) | b64enc() | quote() }}
  generic-oauth-client-secret: {{ Values.concourse.genericOauthClientSecret | default("", true) | b64enc() | quote() }}
  encryption-key: {{ Values.concourse.encryptionKey | default("", true) | b64enc() | quote() }}
  old-encryption-key: {{ Values.concourse.oldEncryptionKey | default("", true) | b64enc() | quote() }}
