apiVersion: v1
kind: Service
metadata:
  name: {{ self.concourse__web__fullname() }}
  labels:
    app: {{ self.concourse__web__fullname() }}
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    release: "{{ Release.Name }}"
    heritage: "{{ Release.Service }}"
spec:
  type: {{ Values.web.service.type }}
  ports:
    - name: atc
      port: {{ Values.concourse.atcPort }}
      targetPort: atc
      {%- if ("NodePort"==Values.web.service.type) and Values.web.service.atcNodePort %}
      nodePort: {{ Values.web.service.atcNodePort }}
      {%- endif %}
    - name: tsa
      port: {{ Values.concourse.tsaPort }}
      targetPort: tsa
      {%- if ("NodePort"==Values.web.service.type) and Values.web.service.tsaNodePort %}
      nodePort: {{ Values.web.service.tsaNodePort }}
      {%- endif %}
  selector:
    app: {{ self.concourse__web__fullname() }}
