apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ self.nginx-lego__fullname() }}-default-backend
  labels:
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
spec:
  replicas: {{ Values.default.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ self.nginx-lego__fullname() }}-default-backend
    spec:
      containers:
      - name: {{ self.nginx-lego__fullname() }}-default-backend
        image: "{{ Values.default.image.repository }}:{{ Values.default.image.tag }}"
        imagePullPolicy: {{ Values.default.image.pullPolicy | quote() }}
        ports:
        - containerPort: 8080
        resources:
{{ toYaml(Values.default.resources) | indent(10) }}