apiVersion: v1
kind: Service
metadata:
  name: {{ self.nginx-lego__fullname() }}-default-backend
  labels:
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: {{ self.nginx-lego__fullname() }}-default-backend
