{%- if Values.nginx.monitoring %}
apiVersion: v1
kind: Service
metadata:
  name: {{ self.nginx-lego__fullname() }}-monitoring
  labels:
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
spec:
  type: ClusterIP
  ports:
  - port: 18080
    name: vts-stats
  selector:
    app: {{ self.nginx-lego__fullname() }}
{%- endif %}