apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ self.mysql__fullname() }}
  labels:
    app: {{ self.mysql__fullname() }}
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    release: "{{ Release.Name }}"
    heritage: "{{ Release.Service }}"
spec:
  template:
    metadata:
      labels:
        app: {{ self.mysql__fullname() }}
    spec:
      initContainers:
      - name: "remove-lost-found"
        image: "busybox:1.25.0"
        imagePullPolicy: {{ Values.imagePullPolicy | quote() }}
        command:  ["rm", "-fr", "/var/lib/mysql/lost+found"]
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
          {%- if Values.persistence.subPath %}
          subPath: {{ Values.persistence.subPath }}
          {%- endif %}
      containers:
      - name: {{ self.mysql__fullname() }}
        image: "{{ Values.image }}:{{ Values.imageTag }}"
        imagePullPolicy: {{ Values.imagePullPolicy | quote() }}
        resources:
{{ toYaml(Values.resources) | indent(10) }}
        env:
        {%- if Values.mysqlAllowEmptyPassword %}
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "true"
        {%- else %}
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ self.mysql__fullname() }}
              key: mysql-root-password
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ self.mysql__fullname() }}
              key: mysql-password
        {%- endif %}
        - name: MYSQL_USER
          value: {{ Values.mysqlUser | default("", true) | quote() }}
        - name: MYSQL_DATABASE
          value: {{ Values.mysqlDatabase | default("", true) | quote() }}
        ports:
        - name: mysql
          containerPort: 3306
        livenessProbe:
          exec:
            command:
            {%- if Values.mysqlAllowEmptyPassword %}
            - mysqladmin
            - ping
            {%- else %}
            - sh
            - -c
            - "mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}"
            {%- endif %}
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            {%- if Values.mysqlAllowEmptyPassword %}
            - mysqladmin
            - ping
            {%- else %}
            - sh
            - -c
            - "mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}"
            {%- endif %}
          initialDelaySeconds: 5
          timeoutSeconds: 1
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
          {%- if Values.persistence.subPath %}
          subPath: {{ Values.persistence.subPath }}
          {%- endif %}
        {%- if Values.configurationFiles %}
        - name: configurations
          mountPath: /etc/mysql/conf.d
        {%- endif %}
      volumes:
      {%- if Values.configurationFiles %}
      - name: configurations
        configMap:
          name: {{ self.mysql__fullname() }}
      {%- endif %}
      - name: data
      {%- if Values.persistence.enabled %}
        persistentVolumeClaim:
          claimName: {{ Values.persistence.existingClaim | default  (self.mysql__fullname()) }}
      {%- else %}
        emptyDir: {}
      {%- endif -%}
