apiVersion: v1
kind: Service
metadata:
  name: {{ self.factorio__fullname() }}
  labels:
    app: {{ self.factorio__fullname() }}
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    release: "{{ Release.Name }}"
    heritage: "{{ Release.Service }}"
spec:
  type: {{ Values.factorioServer.serviceType }}
  ports:
  - name: factorio
    port: {{ Values.factorioServer.port | int() }}
    targetPort: factorio
    protocol: UDP
  selector:
    app: {{ self.factorio__fullname() }}
