{%- if Values.factorioServer.rcon.enabled %}
apiVersion: v1
kind: Service
metadata:
  name: "{{ self.factorio__fullname() }}-rcon"
  labels:
    app: {{ self.factorio__fullname() }}
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    release: "{{ Release.Name }}"
    heritage: "{{ Release.Service }}"
spec:
  type: {{ Values.factorioServer.rcon.serviceType }}
  ports:
  - name: rcon
    port: {{ Values.factorioServer.rcon.port }}
    targetPort: rcon
    protocol: TCP
  selector:
    app: {{ self.factorio__fullname() }}
{%- endif %}
