apiVersion: v1
kind: Secret
metadata:
  name: {{ self.factorio__fullname() }}
  labels:
    app: {{ self.factorio__fullname() }}
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    release: "{{ Release.Name }}"
    heritage: "{{ Release.Service }}"
type: Opaque
data:
  server-password: {{ Values.factorioServer.password | default("", true) | b64enc() | quote() }}
  rcon-password: {{ Values.factorioServer.rcon.password | default("", true) | b64enc() | quote() }}
  factorio-username: {{ Values.factorio.user.username | default("", true) | b64enc() | quote() }}
  factorio-password: {{ Values.factorio.user.password | default("", true) | b64enc() | quote() }}
