{%- if Values.linkerd.ingress.enabled -%}
{%- set globalContext = . -%}
{%- set servicePort = Values.linkerd.httpPort -%}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
  {%- for key, value in Values.linkerd.ingress.annotations.iteritems() %}
    {{ key }}: {{ value | quote() }}
  {%- endfor %}
  labels:
    app: {{ self.linkerd__fullname() }}
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    component: "{{ Values.linkerd.name }}"
    heritage: "{{ Release.Service }}"
    release: "{{ Release.Name }}"
  name: {{ self.linkerd__fullname() }}
spec:
  rules:
  {%- for item in Values.linkerd.ingress.hosts %}
    - host: {{ item }}
      http:
        paths:
          - backend:
              serviceName: {{ template "linkerd.fullname" globalContext }}
              servicePort: {{ servicePort }}
  {%- endfor -%}
  {%- if Values.linkerd.ingress.tls %}
  tls:
{{ toYaml(Values.linkerd.ingress.tls) | indent(4) }}
  {%- endif -%}
{%- endif -%}
