
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-dokuwiki-apache
  labels:
    app: test-dokuwiki
    chart: "dokuwiki-0.2.0"
    release: "test"
    heritage: "dokuwiki"
  annotations:
    volume.alpha.kubernetes.io/storage-class: default
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-dokuwiki-dokuwiki
  labels:
    app: test-dokuwiki
    chart: "dokuwiki-0.2.0"
    release: "test"
    heritage: "dokuwiki"
  annotations:
    volume.alpha.kubernetes.io/storage-class: default
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "8Gi"

---

apiVersion: v1
kind: Secret
metadata:
  name: test-dokuwiki
  labels:
    app: test-dokuwiki
    chart: "dokuwiki-0.2.0"
    release: "test"
    heritage: "dokuwiki"
type: Opaque
data:
  dokuwiki-password: "CnJpYmJueWpqcmYK"


---

apiVersion: v1
kind: Service
metadata:
  name: test-dokuwiki
  labels:
    app: test-dokuwiki
    chart: "dokuwiki-0.2.0"
    release: "test"
    heritage: "dokuwiki"
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: https
    port: 443
    targetPort: https
  selector:
    app: test-dokuwiki


---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test-dokuwiki
  labels:
    app: test-dokuwiki
    chart: "dokuwiki-0.2.0"
    release: "test"
    heritage: "dokuwiki"
spec:
  template:
    metadata:
      labels:
        app: test-dokuwiki
    spec:
      containers:
      - name: test-dokuwiki
        image: "bitnami/dokuwiki:20160626a-r9"
        imagePullPolicy: ""
        env:
        - name: DOKUWIKI_USERNAME
          value: "user"
        - name: DOKUWIKI_FULL_NAME
          value: "Full Name"
        - name: DOKUWIKI_PASSWORD
          valueFrom:
            secretKeyRef:
              name: test-dokuwiki
              key: dokuwiki-password
        - name: DOKUWIKI_EMAIL
          value: "user@example.com"
        - name: DOKUWIKI_WIKI_NAME
          value: "My Wiki"
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        livenessProbe:
          httpGet:
            path: /doku.php
            port: http
          initialDelaySeconds: 120
          timeoutSeconds: 5
          failureThreshold: 6
        readinessProbe:
          httpGet:
            path: /doku.php
            port: http
          initialDelaySeconds: 30
          timeoutSeconds: 3
          periodSeconds: 5
        resources:
          requests: {cpu: 300m, memory: 512Mi}
        volumeMounts:
        - name: dokuwiki-data
          mountPath: /bitnami/dokuwiki
        - name: apache-data
          mountPath: /bitnami/apache
      volumes:
      - name: dokuwiki-data
        persistentVolumeClaim:
          claimName: test-dokuwiki-dokuwiki
      - name: apache-data
        persistentVolumeClaim:
          claimName: test-dokuwiki-apache