{%- if Values.persistence.enabled -%}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ self.fullname() }}-apache
spec:
  accessModes:
    - {{ Values.persistence.apache.accessMode | quote() }}
  resources:
    requests:
      storage: {{ Values.persistence.apache.size | quote() }}
{%- if Values.persistence.apache.storageClass %}
{%- if ("-"==Values.persistence.apache.storageClass) %}
  storageClassName: ""
{%- else %}
  storageClassName: "{{ Values.persistence.apache.storageClass }}"
{%- endif %}
{%- endif %}
{%- endif -%}
