{%- if Values.persistence.enabled -%}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ self.fullname() }}-owncloud
spec:
  accessModes:
    - {{ Values.persistence.owncloud.accessMode | quote() }}
  resources:
    requests:
      storage: {{ Values.persistence.owncloud.size | quote() }}
{%- if Values.persistence.owncloud.storageClass %}
{%- if ("-"==Values.persistence.owncloud.storageClass) %}
  storageClassName: ""
{%- else %}
  storageClassName: "{{ Values.persistence.owncloud.storageClass }}"
{%- endif %}
{%- endif %}
{%- endif -%}
