apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ self.centrifugo__fullname() }}-config
  labels:
    heritage: {{ Release.Service }}
    release: {{ Release.Name }}
    chart: {{ Chart.Name }}-{{ Chart.Version }}
    app: {{ self.centrifugo__name() }}
data:
  config.json: |-
{{ toJson(Values.config) | indent(4) }}