apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ self.centrifugo__fullname() }}
  labels:
    heritage: {{ Release.Service }}
    release: {{ Release.Name }}
    chart: {{ Chart.Name }}-{{ Chart.Version }}
    app: {{ self.centrifugo__name() }}
spec:
  replicas: {{ Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      annotations:
        checksum/config: ""
      labels:
        app: {{ self.centrifugo__name() }}
        release: {{ Release.Name }}
    spec:
      containers:
      - name: {{ Chart.Name }}
        image: "{{ Values.image.repository }}:{{ Values.image.tag }}"
        imagePullPolicy: {{ Values.image.pullPolicy }}
        command:
        - centrifugo
        args:
        {%- for arg in Values.args %}
        - {{ arg }}
        {%- endfor %}
        env:
        - name: CENTRIFUGO_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ self.centrifugo__fullname() }}
              key: admin-password
        - name: CENTRIFUGO_ADMIN_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ self.centrifugo__fullname() }}
              key: admin-secret
        - name: CENTRIFUGO_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ self.centrifugo__fullname() }}
              key: secret
        volumeMounts:
        - name: "{{ self.centrifugo__fullname() }}-config"
          mountPath: "/centrifugo"
          readOnly: true
        ports:
        - name: http
          containerPort: {{ Values.service.port }}
        livenessProbe:
          httpGet:
            path: /connection
            port: {{ Values.service.port }}
        readinessProbe:
          httpGet:
            path: /connection
            port: {{ Values.service.port }}
        resources:
{{ toYaml(Values.resources) | indent(10) }}
      volumes:
      - name: {{ self.centrifugo__fullname() }}-config
        configMap:
          name: {{ self.centrifugo__fullname() }}-config