apiVersion: v1
kind: Secret
metadata:
  name: {{ self.centrifugo__fullname() }}
  labels:
    app: {{ self.centrifugo__name() }}
    chart: {{ Chart.Name }}-{{ Chart.Version }}
    release: {{ Release.Name }}
    heritage: {{ Release.Service }}
type: Opaque
data:
  {%- if Values.admin.password %}
  admin-password: {{ Values.admin.password | b64enc() | quote() }}
  {%- else %}
  admin-password: {{ randAlphaNum(10) | b64enc() | quote() }}
  {%- endif %}
  {%- if Values.admin.secret %}
  admin-secret: {{ Values.admin.secret | b64enc() | quote() }}
  {%- else %}
  admin-secret: {{ randAlphaNum(10) | b64enc() | quote() }}
  {%- endif %}
  {%- if Values.secret %}
  secret: {{ Values.secret | b64enc() | quote() }}
  {%- else %}
  secret: {{ randAlphaNum(10) | b64enc() | quote() }}
  {%- endif %}