apiVersion: v1
kind: Service
metadata:
{%- if Values.service.annotations %}
  annotations:
{{ toYaml(Values.service.annotations) | indent(4) }}
{%- endif %}
  labels:
    heritage: {{ Release.Service }}
    release: {{ Release.Name }}
    chart: {{ Chart.Name }}-{{ Chart.Version }}
    app: {{ self.centrifugo__name() }}
  name: {{ self.centrifugo__fullname() }}
spec:
  type: "{{ Values.service.type }}"
  clusterIP: "{{ Values.service.clusterIP }}"
{%- if Values.service.externalIPs %}
  externalIPs:
{{ toYaml(Values.service.externalIPs) | indent(4) }}
{%- endif %}
{%- if Values.service.loadBalancerIP %}
  loadBalancerIP: "{{ Values.service.loadBalancerIP }}"
{%- endif %}
{%- if Values.service.loadBalancerSourceRanges %}
  loadBalancerSourceRanges:
{{ toYaml(Values.service.loadBalancerSourceRanges) | indent(4) }}
{%- endif %}
  ports:
    - name: http
      port: {{ Values.service.port }}
      protocol: TCP
      targetPort: http
      {%- if ((Values.service.type=="NodePort") and ( not  ( empty  Values.service.nodePort))) %}
      nodePort: {{ Values.service.nodePort }}
      {%- endif %}
  selector:
    app: {{ self.centrifugo__name() }}
    release: {{ Release.Name }}
