apiVersion: v1
kind: Service
metadata:
  name: {{ Release.Name }}-zeppelin
  labels:
    app: {{ self.zeppelin__name() }}
    chart: {{ Chart.Name }}-{{ Chart.Version | replace("+","_") }}
    release: {{ Release.Name }}
    heritage: {{ Release.Service }}
spec:
  type: ClusterIP
  ports:
  - port: 8080
    name: web
  selector:
    app: {{ self.zeppelin__name() }}
    release: {{ Release.Name }}