



---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-postgresql
  labels:
    app: test-postgresql
    chart: "postgresql-0.8.3"
    release: "test"
    heritage: "postgresql"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "8Gi"

---

apiVersion: v1
kind: Secret
metadata:
  name: test-postgresql
  labels:
    app: test-postgresql
    chart: "postgresql-0.8.3"
    release: "test"
    heritage: "postgresql"
type: Opaque
data:
  postgres-password: "Cnl6enNlcWVxemsK"


---

apiVersion: v1
kind: Service
metadata:
  name: test-postgresql
  labels:
    app: test-postgresql
    chart: "postgresql-0.8.3"
    release: "test"
    heritage: "postgresql"
spec:
  type: ClusterIP
  ports:
  - name: postgresql
    port: 5432
    targetPort: postgresql
  selector:
    app: test-postgresql

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test-postgresql
  labels:
    app: test-postgresql
    chart: "postgresql-0.8.3"
    release: "test"
    heritage: "postgresql"
spec:
  template:
    metadata:
      labels:
        app: test-postgresql
    spec:
      containers:
      - name: test-postgresql
        image: "postgres:9.6.2"
        imagePullPolicy: ""
        env:
        - name: POSTGRES_USER
          value: "postgres"
          # Required for pg_isready in the health probes.
        - name: PGUSER
          value: "postgres"
        - name: POSTGRES_DB
          value: ""
        - name: POSTGRES_INITDB_ARGS
          value: ""
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: test-postgresql
              key: postgres-password
        - name: POD_IP
          valueFrom: { fieldRef: { fieldPath: status.podIP } }
        ports:
        - name: postgresql
          containerPort: 5432
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - exec pg_isready --host $POD_IP
          initialDelaySeconds: 60
          timeoutSeconds: 5
          failureThreshold: 6
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - exec pg_isready --host $POD_IP
          initialDelaySeconds: 5
          timeoutSeconds: 3
          periodSeconds: 5
        resources:
          requests: {cpu: 100m, memory: 256Mi}
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data/pgdata
          subPath: postgresql-db
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: test-postgresql