apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ self.fullname() }}
  labels:
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    app: "{{ self.name() }}"
    heritage: "{{ Release.Service }}"
    release: "{{ Release.Name }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: "{{ self.name() }}"
        release: "{{ Release.Name }}"
    spec:
      serviceAccountName: {%- if Values.rbac.create %}{{ self.fullname() }}{%- else %}"{{ Values.rbac.serviceAccountName }}"{%- endif %}
      containers:
      - name: operator
        image: {{ Values.image }}:{{ Values.imageTag }}
        args:
        - run
        - --cloud-provider={{ Values.cloudProvider }}
        - --cloud-config={{ Values.cloudConfig }}
        - --v={{ Values.logLevel }}
        - --rbac={{ Values.rbac.create }}
        ports:
        - containerPort: 56790
          name: http
          protocol: TCP
{%- if Values.persistence.enabled %}
        volumeMounts:
          - mountPath: {{ Values.cloudConfig | quote() }}
            name: cloudconfig
            readOnly: true
      volumes:
        - hostPath:
            path: {{ Values.persistence.hostPath | quote() }}
          name: cloudconfig
{%- endif -%}
    {%- if Values.nodeSelector %}
      nodeSelector:
{{ toYaml(Values.nodeSelector) | indent(8) }}
{%- endif -%}
