apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ self.hadoop__fullname() }}-yarn-nm
  labels:
    app: {{ self.hadoop__name() }}
    chart: {{ Chart.Name }}-{{ Chart.Version }}
    release: {{ Release.Name }}
    heritage: {{ Release.Service }}
    component: yarn-nm
spec:
  selector:
    matchLabels:
      app: {{ self.hadoop__name() }}
      release: {{ Release.Name }}
      component: yarn-nm
  minAvailable: {{ Values.yarn.nodeManager.pdbMinAvailable }}
  