# Service to access the yarn web ui
apiVersion: v1
kind: Service
metadata:
  name: {{ self.hadoop__fullname() }}-yarn-ui
  labels:
    app: {{ self.hadoop__name() }}
    chart: {{ Chart.Name }}-{{ Chart.Version | replace("+","_") }}
    release: {{ Release.Name }}
    heritage: {{ Release.Service }}
    component: yarn-ui
spec:
  ports:
  - port: 8088
    name: web
  selector:
    app: {{ self.hadoop__name() }}
    component: yarn-rm