
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-traefik
  labels:
    app: test-traefik
    chart: "traefik-1.11.5"
    release: "test"
    heritage: "traefik"
data:
  traefik.toml: |
    # traefik.toml
    logLevel = "INFO"
    defaultEntryPoints = ["http"]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
      compress = True
    [kubernetes]


---




---




---




---




---




---

apiVersion: v1
kind: Service
metadata:
  name: test-traefik
  labels:
    app: test-traefik
    chart: "traefik-1.11.5"
    release: "test"
    heritage: "traefik"
  annotations:
spec:
  type: LoadBalancer
  selector:
    app: test-traefik
  ports:
  - port: 80
    name: http
  - port: 443
    name: https
    targetPort: 80


---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test-traefik
  labels:
    app: test-traefik
    chart: "traefik-1.11.5"
    release: "test"
    heritage: "traefik"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-traefik
  template:
    metadata:
      labels:
        app: test-traefik
        chart: "traefik-1.11.5"
        release: "test"
        heritage: "traefik"
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 60
      containers:
      - image: traefik:1.3.8
        name: test-traefik
        resources:
          requests:
            cpu: "100m"
            memory: "20Mi"
          limits:
            cpu: "100m"
            memory: "30Mi"
        readinessProbe:
          tcpSocket:
            port: 80
          failureThreshold: 1
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        livenessProbe:
          tcpSocket:
            port: 80
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        volumeMounts:
        - mountPath: /config
          name: config
        ports:
        - containerPort: 80
        - containerPort: 443
        args:
        - --configfile=/config/traefik.toml
      volumes:
      - name: config
        configMap:
          name: test-traefik