apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ self.mariadb__fullname() }}
  labels:
    app: {{ self.mariadb__fullname() }}
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    release: "{{ Release.Name }}"
    heritage: "{{ Release.Service }}"
data:
  my.cnf: |-
{%- if Values.config %}
{{ Values.config | indent(4) }}
{%- endif -%}
