apiVersion: v1
kind: Service
metadata:
  name: {{ self.mariadb__fullname() }}
  labels:
    app: {{ self.mariadb__fullname() }}
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    release: "{{ Release.Name }}"
    heritage: "{{ Release.Service }}"
{%- if Values.metrics.enabled %}
  annotations:
{{ toYaml(Values.metrics.annotations) | indent(4) }}
{%- endif %}
spec:
  type: {{ Values.serviceType }}
  ports:
  - name: mysql
    port: 3306
    targetPort: mysql
{%- if Values.metrics.enabled %}
  - name: metrics
    port: 9104
    targetPort: metrics
{%- endif %}
  selector:
    app: {{ self.mariadb__fullname() }}
