apiVersion: v1
kind: Service
metadata:
  name: {{ self.kapacitor__fullname() }}
  labels:
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    release: "{{ Release.Name }}"
    heritage: "{{ Release.Service }}"
    app: {{ self.kapacitor__fullname() }}
spec:
  type: {{ Values.service.type }}
  ports:
  - port: 9092
    targetPort: 9092
    name: api
  selector:
    app: {{ self.kapacitor__fullname() }}
