
apiVersion: v1
kind: Service
metadata:
  name: test-zetcd
  labels:
    app: zetcd
    chart: zetcd-0.1.3
    release: test
    heritage: zetcd
spec:
  type: ClusterIP
  ports:
    - port: 2181
      targetPort: 2181
      protocol: TCP
      name: zetcd
  selector:
    app: zetcd
    release: test


---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test-zetcd
  labels:
    app: zetcd
    chart: zetcd-0.1.3
    release: test
    heritage: zetcd
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zetcd
        release: test
    spec:
      containers:
        - name: zetcd
          image: "quay.io/coreos/zetcd:v0.0.3"
          imagePullPolicy: IfNotPresent
          command:
            - "/usr/local/bin/zetcd"
            - "-zkaddr"
            - "0.0.0.0:2181"
            - "-endpoints"
            - "-client:2379"
          ports:
            - containerPort: 2181
          livenessProbe:
            tcpSocket:
              port: 2181
          readinessProbe:
            tcpSocket:
              port: 2181
          resources:
            {}