
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-consul-tests
data:
  run.sh: |-
    @test "Testing Consul cluster has quorum" {
      for i in {0..2}; do
        if [ `kubectl exec test-consul-$i consul members --namespace=dev | grep server | wc -l` -ge "3" ]; then
          echo "test-consul-$i OK. consul members returning at least 3 records."
        else
          echo "test-consul-$i ERROR. consul members returning less than 3 records."
          exit 1
        fi
      done
    }


---

apiVersion: v1
kind: Secret
metadata:
  name: test-consul-gossip-key
type: Opaque
data:
  gossip-key: CnFobHlpY2N0dHdnYWhlZmdpa2p5cm9qego=
---
apiVersion: v1
kind: Service
metadata:
  name: "test-consul-ui"
  labels:
    heritage: "consul"
    release: "test"
    chart: "consul-0.4.2"
    component: "test-consul"
spec:
  ports:
  - name: http
    port: 8500
  selector:
    component: "test-consul"
  type: "NodePort"
---
apiVersion: v1
kind: Service
metadata:
  name: "test-consul"
  labels:
    heritage: "consul"
    release: "test"
    chart: "consul-0.4.2"
    component: "test-consul"
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
  - name: http
    port: 8500
  - name: rpc
    port: 8400
  - name: serflan-tcp
    protocol: "TCP"
    port: 8301
  - name: serflan-udp
    protocol: "UDP"
    port: 8301
  - name: serfwan-tcp
    protocol: "TCP"
    port: 8302
  - name: serfwan-udp
    protocol: "UDP"
    port: 8302
  - name: server
    port: 8300
  - name: consuldns-tcp
    port: 8600
  - name: consuldns-udp
    protocol: "UDP"
    port: 8600
  clusterIP: None
  selector:
    component: "test-consul"
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: "test-consul"
  labels:
    heritage: "consul"
    release: "test"
    chart: "consul-0.4.2"
    component: "test-consul"
spec:
  serviceName: "test-consul"
  replicas: 3
  template:
    metadata:
      name: "test-consul"
      labels:
        heritage: "consul"
        release: "test"
        chart: "consul-0.4.2"
        component: "test-consul"
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: "test-consul"
        image: "consul:0.8.3"
        imagePullPolicy: "Always"
        ports:
        - name: http
          containerPort: 8500
        - name: rpc
          containerPort: 8400
        - name: serflan-tcp
          protocol: "TCP"
          containerPort: 8301
        - name: serflan-udp
          protocol: "UDP"
          containerPort: 8301
        - name: serfwan-tcp
          protocol: "TCP"
          containerPort: 8302
        - name: serfwan-udp
          protocol: "UDP"
          containerPort: 8302
        - name: server
          containerPort: 8300
        - name: consuldns-tcp
          containerPort: 8600
        - name: consuldns-udp
          protocol: "UDP"
          containerPort: 8600
        resources:
          {}
        env:
        - name: INITIAL_CLUSTER_SIZE
          value: "3"
        - name: STATEFULSET_NAME
          value: "test-consul"
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: STATEFULSET_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: DNSPORT
          value: "8600"
        volumeMounts:
        - name: datadir
          mountPath: /var/lib/consul
        - name: gossip-key
          mountPath: /etc/consul/secrets
          readOnly: true
        livenessProbe:
          exec:
            command:
            - consul
            - members
          initialDelaySeconds: 300
          timeoutSeconds: 5
        command:
          - "/bin/sh"
          - "-ec"
          - |
            IP=$(hostname -i)
            if [ -e /etc/consul/secrets/gossip-key ]; then
              echo "{\"encrypt\": \"$(base64 /etc/consul/secrets/gossip-key)\"}" > /etc/consul/encrypt.json
              GOSSIP_KEY="-config-file /etc/consul/encrypt.json"
            fi

            for i in $(seq 0 $((${INITIAL_CLUSTER_SIZE} - 1))); do
                while true; do
                    echo "Waiting for ${STATEFULSET_NAME}-${i}.${STATEFULSET_NAME} to come up"
                    ping -W 1 -c 1 ${STATEFULSET_NAME}-${i}.${STATEFULSET_NAME}.${STATEFULSET_NAMESPACE}.svc > /dev/null && break
                    sleep 1s
                done
            done

            PEERS=""
            for i in $(seq 0 $((${INITIAL_CLUSTER_SIZE} - 1))); do
                PEERS="${PEERS}${PEERS:+ } -retry-join $(ping -c 1 ${STATEFULSET_NAME}-${i}.${STATEFULSET_NAME}.${STATEFULSET_NAMESPACE}.svc | awk -F'[()]' '/PING/{print $2}')"
            done

            exec /bin/consul agent \
              -ui \
              -data-dir=/var/lib/consul \
              -server \
              -bootstrap-expect=${INITIAL_CLUSTER_SIZE} \
              -bind=0.0.0.0 \
              -advertise=${IP} \
              ${PEERS} \
              ${GOSSIP_KEY} \
              -client=0.0.0.0 \
              -dns-port=${DNSPORT}
      volumes:
      - name: gossip-key
        secret:
          secretName: test-consul-gossip-key
  volumeClaimTemplates:
  - metadata:
      name: datadir
      annotations:
        volume.alpha.kubernetes.io/storage-class: default
    spec:
      accessModes:
        - "ReadWriteOnce"
      resources:
        requests:
          # upstream recommended max is 700M
          storage: "1Gi"


---

apiVersion: v1
kind: Pod
metadata:
  name: "test-ui-test-yypzv"
  annotations:
    "helm.sh/hook": test-success
spec:
  initContainers:
    - name: test-framework
      image: dduportal/bats:0.4.0
      command:
      - "bash"
      - "-c"
      - |
        set -ex
        # copy bats to tools dir
        cp -R /usr/local/libexec/ /tools/bats/
      volumeMounts:
      - mountPath: /tools
        name: tools
  containers:
    - name: test-ui-test
      image: lachlanevenson/k8s-kubectl:v1.4.8-bash
      command: ["/tools/bats/bats", "-t", "/tests/run.sh"]
      volumeMounts:
      - mountPath: /tests
        name: tests
        readOnly: true
      - mountPath: /tools
        name: tools
  volumes:
  - name: tests
    configMap:
      name: test-consul-tests
  - name: tools
    emptyDir: {}
  restartPolicy: Never