apiVersion: v1
kind: Secret
metadata:
  name: {{ self.fullname() }}
  labels:
    app: {{ self.name() }}
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    release: "{{ Release.Name }}"
    heritage: "{{ Release.Service }}"
type: Opaque
data:
  {%- if Values.server.masterKey %}
  master-key: {{ Values.server.masterKey | b64enc() | quote() }}
  {%- else %}
  master-key: {{ randAlphaNum(10) | b64enc() | quote() }}
  {%- endif %}
  {%- if Values.dashboard.enabled %}
  {%- if Values.dashboard.password %}
  parse-dashboard-password: {{ Values.dashboard.password | b64enc() | quote() }}
  {%- else %}
  parse-dashboard-password: {{ randAlphaNum(10) | b64enc() | quote() }}
  {%- endif %}
  {%- endif %}
