apiVersion: v1
kind: Service
metadata:
  name: {{ self.fullname() }}
  labels:
    app: {{ self.name() }}
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    release: "{{ Release.Name }}"
    heritage: "{{ Release.Service }}"
spec:
  type: {{ Values.serviceType }}
  {%- if Values.serviceType=="LoadBalancer" %}
  loadBalancerIP: {{ Values.loadBalancerIP | quote() }}
  {%- endif %}
  ports:
  - name: server-http
    port: {{ Values.server.port }}
    targetPort: server-http
  - name: dashboard-http
    port: 80
    targetPort: dashboard-http
  selector:
    app: {{ self.name() }}
    release: "{{ Release.Name }}"
