{%- if Values.persistence.gitlabData.enabled %}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ self.gitlab-ee__fullname() }}-data
  annotations:
  {%- if Values.persistence.gitlabData.storageClass %}
    volume.beta.kubernetes.io/storage-class: {{ Values.persistence.gitlabData.storageClass | quote() }}
  {%- else %}
    volume.alpha.kubernetes.io/storage-class: default
  {%- endif %}
spec:
  accessModes:
    - {{ Values.persistence.gitlabData.accessMode | quote() }}
  resources:
    requests:
      storage: {{ Values.persistence.gitlabData.size | quote() }}
{%- endif %}
