{%- if Values.persistence.gitlabEtc.enabled %}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ self.gitlab-ee__fullname() }}-etc
  annotations:
  {%- if Values.persistence.gitlabEtc.storageClass %}
    volume.beta.kubernetes.io/storage-class: {{ Values.persistence.gitlabEtc.storageClass | quote() }}
  {%- else %}
    volume.alpha.kubernetes.io/storage-class: default
  {%- endif %}
spec:
  accessModes:
    - {{ Values.persistence.gitlabEtc.accessMode | quote() }}
  resources:
    requests:
      storage: {{ Values.persistence.gitlabEtc.size | quote() }}
{%- endif %}
