{%- if Values.webhookRelay.enabled %}
apiVersion: v1
kind: Secret
metadata:
  name: {{ self.keel__fullname() }}-webhookrelay
  namespace: kube-system
  labels:
    app: {{ self.keel__name() }}
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    release: "{{ Release.Name }}"
    heritage: "{{ Release.Service }}"
type: Opaque
data:
  key: {{ Values.webhookRelay.key | b64enc() }}
  secret:  {{ Values.webhookRelay.secret | b64enc() }}
{%- endif %}
