apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ self.keel__fullname() }}
  namespace: kube-system
  labels:
    app: {{ self.keel__name() }}
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    release: "{{ Release.Name }}"
    heritage: "{{ Release.Service }}"
