apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ self.orangehrm__fullname() }}
  labels:
    app: {{ self.orangehrm__fullname() }}
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    release: "{{ Release.Name }}"
    heritage: "{{ Release.Service }}"
spec:
  template:
    metadata:
      labels:
        app: {{ self.orangehrm__fullname() }}
    spec:
      containers:
      - name: {{ self.orangehrm__fullname() }}
        image: "{{ Values.image }}"
        imagePullPolicy: {{ Values.imagePullPolicy | default("", true) | quote() }}
        env:
        - name: MARIADB_HOST
          value: {{ self.orangehrm__mariadb__fullname() }}
        - name: MARIADB_PORT_NUMBER
          value: "3306"
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ self.orangehrm__mariadb__fullname() }}
              key: mariadb-root-password
        - name: ORANGEHRM_USERNAME
          value: {{ Values.orangehrmUsername | default("", true) | quote() }}
        - name: ORANGEHRM_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ self.orangehrm__fullname() }}
              key: orangehrm-password
        - name: SMTP_HOST
          value: {{ Values.smtpHost | default("", true) | quote() }}
        - name: SMTP_PORT
          value: {{ Values.smtpPort | default("", true) | quote() }}
        - name: SMTP_USER
          value: {{ Values.smtpUser | default("", true) | quote() }}
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ self.orangehrm__fullname() }}
              key: smtp-password
        - name: SMTP_PROTOCOL
          value: {{ Values.smtpProtocol | default("none", true) | quote() }}
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        livenessProbe:
          httpGet:
            path: /symfony/web/index.php
            port: http
          initialDelaySeconds: 120
        readinessProbe:
          httpGet:
            path: /symfony/web/index.php
            port: http
          initialDelaySeconds: 30
        resources:
{{ toYaml(Values.resources) | indent(10) }}
        volumeMounts:
        - name: orangehrm-data
          mountPath: /bitnami/orangehrm
        - name: apache-data
          mountPath: /bitnami/apache
      volumes:
      - name: orangehrm-data
      {%- if Values.persistence.enabled %}
        persistentVolumeClaim:
          claimName: {{ self.orangehrm__fullname() }}-orangehrm
      {%- else %}
        emptyDir: {}
      {%- endif %}
      - name: apache-data
      {%- if Values.persistence.enabled %}
        persistentVolumeClaim:
          claimName: {{ self.orangehrm__fullname() }}-apache
      {%- else %}
        emptyDir: {}
      {%- endif %}
