{%- if Values.ingress.enabled %}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
{%- if Values.ingress.annotations %}
  annotations:
{{ toYaml(Values.ingress.annotations) | indent(4) }}
{%- endif %}
  name: {{ self.redmine__fullname() }}
spec:
  rules:
  - host: {{ Values.ingress.hostname | quote() }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ self.redmine__fullname() }}
          servicePort: 80
{%- if Values.ingress.tls %}
  tls:
{{ toYaml(Values.ingress.tls) | indent(4) }}
{%- endif -%}
{%- endif %}
