apiVersion: v1
kind: Service
metadata:
  name: {{ self.redmine__fullname() }}
  labels:
    app: {{ self.redmine__fullname() }}
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    release: "{{ Release.Name }}"
    heritage: "{{ Release.Service }}"
spec:
  type: {{ Values.serviceType }}
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: {{ self.redmine__fullname() }}
  {%- if Values.serviceType=="LoadBalancer" %}
  loadBalancerSourceRanges: {{ Values.serviceLoadBalancerSourceRanges }}
  {%- endif %}
