



---

apiVersion: v1
kind: Secret
metadata:
  name: test-percona
  labels:
    app: test-percona
    chart: "percona-0.3.0"
    release: "test"
    heritage: "percona"
type: Opaque
data:
  mysql-root-password: "CmJkd3l5endwamwK"
  mysql-password: "CmhxYnZxamRzenEK"


---

apiVersion: v1
kind: Service
metadata:
  name: test-percona
  labels:
    app: test-percona
    chart: "percona-0.3.0"
    release: "test"
    heritage: "percona"
spec:
  ports:
  - name: mysql
    port: 3306
    targetPort: mysql
  selector:
    app: test-percona


---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test-percona
  labels:
    app: test-percona
    chart: "percona-0.3.0"
    release: "test"
    heritage: "percona"
spec:
  template:
    metadata:
      labels:
        app: test-percona
    spec:
      initContainers:
      - name: "remove-lost-found"
        image: "busybox:1.25.0" 
        imagePullPolicy: "IfNotPresent"
        command: 
        - "rm"
        - "-fr"
        - "/var/lib/mysql/lost+found"
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
      containers:
      - name: test-percona
        image: "mysql:5.7.17"
        imagePullPolicy: "IfNotPresent"
        resources:
          requests: {cpu: 100m, memory: 256Mi}
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: test-percona
              key: mysql-root-password
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: test-percona
              key: mysql-password
        - name: MYSQL_USER
          value: ""
        - name: MYSQL_DATABASE
          value: ""
        ports:
        - name: mysql
          containerPort: 3306
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - mysqladmin
            - ping
          initialDelaySeconds: 5
          timeoutSeconds: 1
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
      volumes:
      - name: data
        emptyDir: {}