apiVersion: v1
kind: Secret
metadata:
  name: {{ self.phpbb__fullname() }}
  labels:
    app: {{ self.phpbb__fullname() }}
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    release: "{{ Release.Name }}"
    heritage: "{{ Release.Service }}"
type: Opaque
data:
  {%- if Values.phpbbPassword %}
  phpbb-password: {{ Values.phpbbPassword | b64enc() | quote() }}
  {%- else %}
  phpbb-password: {{ randAlphaNum(10) | b64enc() | quote() }}
  {%- endif %}
  smtp-password: {{ Values.smtpPassword | default("", true) | b64enc() | quote() }}
