apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ self.grafana__fullname() }}
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    component: "{{ Values.server.name }}"
    heritage: "{{ Release.Service }}"
    release: "{{ Release.Name }}"
  name: {{ self.grafana__server__fullname() }}-config
data:
  {%- if Values.server.installPlugins -%}
  grafana-install-plugins: {{ Values.server.installPlugins | quote() }}
  {%- endif -%}
{{ toYaml(Values.serverConfigFile) | indent(2) }}
