{%- if Values.server.ingress.enabled -%}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
  {%- for key, value in Values.server.ingress.annotations.iteritems() %}
    {{ key }}: {{ value | quote() }}
  {%- endfor %}
  labels:
    app: {{ self.grafana__fullname() }}
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    component: "{{ Values.server.name }}"
    heritage: "{{ Release.Service }}"
    release: "{{ Release.Name }}"
  name: {{ self.grafana__server__fullname() }}
spec:
  rules:
  {%- for item in Values.server.ingress.hosts %}
    - host: {{ item }}
      http:
        paths:
          - backend:
              serviceName: {{ self.grafana__server__fullname() }}
              servicePort: {{ Values.server.service.httpPort }}
  {%- endfor -%}
  {%- if Values.server.ingress.tls %}
  tls:
{{ toYaml(Values.server.ingress.tls) | indent(4) }}
  {%- endif -%}
{%- endif -%}
