{%- if Values.server.persistentVolume.enabled -%}
{%- if  not  Values.server.persistentVolume.existingClaim -%}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
  {%- if Values.server.persistentVolume.annotations %}
{{ toYaml(Values.server.persistentVolume.annotations) | indent(4) }}
  {%- endif %}
  labels:
    app: {{ self.grafana__fullname() }}
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    component: "{{ Values.server.name }}"
    heritage: "{{ Release.Service }}"
    release: "{{ Release.Name }}"
  name: {{ self.grafana__server__fullname() }}
spec:
  accessModes:
{%- for item in Values.server.persistentVolume.accessModes %}
    - {{ item | quote() }}
{%- endfor %}
  resources:
    requests:
      storage: {{ Values.server.persistentVolume.size | quote() }}
{%- if Values.server.persistentVolume.storageClass %}
{%- if ("-"==Values.server.persistentVolume.storageClass) %}
  storageClassName: ""
{%- else %}
  storageClassName: "{{ Values.server.persistentVolume.storageClass }}"
{%- endif %}
{%- endif %}
{%- endif -%}
{%- endif -%}
