apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ self.grafana__fullname() }}
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    heritage: "{{ Release.Service }}"
    release: "{{ Release.Name }}"
  name: {{ self.grafana__server__fullname() }}
type: Opaque
data:
  {%- if Values.server.adminPassword %}
  grafana-admin-password: {{ Values.server.adminPassword | b64enc() | quote() }}
  {%- else %}
  grafana-admin-password: {{ randAlphaNum(10) | b64enc() | quote() }}
  {%- endif %}
  grafana-admin-user: {{ Values.server.adminUser | b64enc() | quote() }}
