



---

apiVersion: v1
kind: Secret
metadata:
  name: test-mongodb
  labels:
    app: test-mongodb
    chart: "mongodb-0.4.17"
    release: "test"
    heritage: "mongodb"
type: Opaque
data:
  mongodb-root-password: ""
  mongodb-password: ""


---

apiVersion: v1
kind: Service
metadata:
  name: test-mongodb
  labels:
    app: test-mongodb
    chart: "mongodb-0.4.17"
    release: "test"
    heritage: "mongodb"
spec:
  type: ClusterIP
  ports:
  - name: mongodb
    port: 27017
    targetPort: mongodb
  selector:
    app: test-mongodb


---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test-mongodb
  labels:
    app: test-mongodb
    chart: "mongodb-0.4.17"
    release: "test"
    heritage: "mongodb"
spec:
  template:
    metadata:
      labels:
        app: test-mongodb
    spec:
      containers:
      - name: test-mongodb
        image: "bitnami/mongodb:3.4.9-r1"
        imagePullPolicy: ""
        env:
        - name: MONGODB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: test-mongodb
              key: mongodb-root-password
        - name: MONGODB_USERNAME
          value: ""
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: test-mongodb
              key: mongodb-password
        - name: MONGODB_DATABASE
          value: ""
        ports:
        - name: mongodb
          containerPort: 27017
        livenessProbe:
          exec:
            command:
            - mongo
            - --eval
            - "db.adminCommand('ping')"
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - mongo
            - --eval
            - "db.adminCommand('ping')"
          initialDelaySeconds: 5
          timeoutSeconds: 1
        volumeMounts:
        - name: data
          mountPath: /bitnami/mongodb
        resources:
          limits: {cpu: 400m, memory: 1024Mi}
          requests: {cpu: 100m, memory: 256Mi}
      volumes:
      - name: data
        emptyDir: {}