apiVersion: v1
kind: Secret
metadata:
  name: "{{ self.fullname() }}-secrets-{{ Release.Time.Seconds }}"
  labels:
    app: {{ self.fullname() }}
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    release: "{{ Release.Name }}"
    heritage: "{{ Release.Service }}"
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
type: Opaque
data:
  access-id: {{ Values.sumologic.accessId | default("MISSING", true) | b64enc() | quote() }}
  access-key: {{ Values.sumologic.accessKey | default("MISSING", true) | b64enc() | quote() }}
  collector-name: {{ Values.sumologic.collectorName | default("kubernetes", true) | b64enc() | quote() }}
