{%- if Values.rbac.install %}
{%- set serviceName =  self.g2__fullname() -%}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ serviceName }}
  labels:
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    app: "{{ self.g2__fullname() }}"
    heritage: "{{ Release.Service }}"
    release: "{{ Release.Name }}"
subjects:
- kind: ServiceAccount
  name: {{ serviceName }}
  namespace: {{ Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ serviceName }}
{%- endif %}
