



---




---

apiVersion: v1
kind: Secret
metadata:
  name: test-redis
  labels:
    app: test-redis
    chart: "redis-0.10.2"
    release: "test"
    heritage: "redis"
type: Opaque
data:
  redis-password: "MTIzNDU2"

---

apiVersion: v1
kind: Service
metadata:
  name: test-redis
  labels:
    app: test-redis
    chart: "redis-0.10.2"
    release: "test"
    heritage: "redis"
spec:
  type: ClusterIP
  ports:
  - name: redis
    port: 6379
    targetPort: redis
  selector:
    app: test-redis


---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test-redis
  labels:
    app: test-redis
    chart: "redis-0.10.2"
    release: "test"
    heritage: "redis"
spec:
  template:
    metadata:
      labels:
        app: test-redis
    spec:
      containers:
      - name: test-redis
        image: "bitnami/redis:3.2.9-r2"
        imagePullPolicy: "IfNotPresent"
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: test-redis
              key: redis-password
        ports:
        - name: redis
          containerPort: 6379
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          timeoutSeconds: 1
        resources:
          limits: {cpu: 400m, memory: 1024Mi}
          requests: {cpu: 100m, memory: 256Mi}
        volumeMounts:
        - name: redis-data
          mountPath: /bitnami/redis
      volumes:
      - name: redis-data
        emptyDir: {}