



---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-keel
  namespace: kube-system
  labels:
    app: keel
    chart: "keel-0.2.0"
    release: "test"
    heritage: "keel"


---




---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test-keel
  namespace: kube-system
  labels:
    app: keel
    chart: keel-0.2.0
    release: test
    heritage: keel
  annotations:
    kubernetes.io/service-account.name: keel
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: keel
        release: test
    spec:
      containers:
        - name: keel
          image: "karolisr/keel:0.4.2"
          imagePullPolicy: IfNotPresent
          command: ["/bin/keel"]
          env:
            # Enable polling
            - name: POLL
              value: "1"
          ports:
            - containerPort: 9300
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9300
            initialDelaySeconds: 30
            timeoutSeconds: 10
          resources:
            
      nodeSelector:
        {}