
apiVersion: v1
kind: Service
metadata:
  name: test-selenium-hub
  labels:
    app: test-selenium-hub
    chart: "selenium-0.2.0"
    release: "test"
    heritage: "selenium"
spec:
  type: "LoadBalancer"
  sessionAffinity: "None"
  ports:
  - name: hub
    port: 4444
    targetPort: 4444
  selector:
    app: test-selenium-hub


---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test-selenium-hub
  labels:
    chart: "selenium-0.2.0"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: test-selenium-hub
        chart: "selenium-0.2.0"
        release: "test"
        heritage: "selenium"
      annotations: 
    spec:
      containers:
        - name: selenium
          image: "selenium/hub:3.4.0"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4444
              name: http
          livenessProbe:
            httpGet:
              path: /grid/console
              port: 4444
            initialDelaySeconds: 30
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /grid/console
              port: 4444
            timeoutSeconds: 1
          env:
            - name: JAVA_OPTS
              value: "-Xmx400m"
            - name: SE_OPTS
              value: ""
          resources:
            limits: {cpu: '.5', memory: 512Mi}