apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ self.fullname() }}
  labels:
    app: {{ self.name() }}
    chart: {{ Chart.Name }}-{{ Chart.Version | replace("+","_") }}
    release: {{ Release.Name }}
    heritage: {{ Release.Service }}
data:
  config.json: |-
{%- if Values.mcrouterCommandParams.configFile %}{{ range .Files.Lines Values.mcrouterCommandParams.configFile }}
    {{ . }}{%- endif %}
{%- else %}
    {%- if Values.memcached.enabled %}
    {
      "pools": {
        "A": {
          "servers": [
            {%- set global = . %}
            {%- range $i, set e = until (Values.memcached.replicaCount | int)() %}
            "{{ globalRelease.Name }}-memcached-{{ i }}.{{ globalRelease.Name }}-memcached.{{ globalRelease.Namespace }}.svc.cluster.local:11211",
            {%- endif %}
          ]
        }
      },
      "route": "PoolRoute|A"
    }
    {%- endif %}
{%- endif %}