apiVersion: v1
kind: Service
metadata:
  name: {{ self.fullname() }}
  labels:
    app: {{ self.fullname() }}
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    release: "{{ Release.Name }}"
    heritage: "{{ Release.Service }}"
spec:
  clusterIP: None
  ports:
  - name: mcrouter-port
    port: {{ Values.mcrouterCommandParams.port }}
    targetPort: mcrouter-port
  selector:
    app: {{ self.fullname() }}
