apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ self.heapster__fullname() }}
  labels:
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
  {%- if Values.labels -%}    
    {%- for key, value in Values.labels.iteritems() %}
    {{ key }}: {{ value }}
    {%- endfor %}
  {%- endif %}
spec:
  replicas: {{ Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ self.heapster__fullname() }}
    spec:
      serviceAccountName: {%- if Values.rbac.create %}{{ self.heapster__fullname() }}{%- else %}"{{ Values.rbac.serviceAccountName }}"{%- endif %}
{%- if Values.nodeSelector %}
      nodeSelector:
{{ toYaml(Values.nodeSelector) | indent(8) }}
{%- endif %}
      containers:
      - name: {{ Chart.Name }}
        image: "{{ Values.image.repository }}:{{ Values.image.tag }}"
        imagePullPolicy: {{ Values.image.pullPolicy }}
        ports:
        - containerPort: {{ Values.service.internalPort }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ Values.service.internalPort }}
          initialDelaySeconds: 180
          timeoutSeconds: 5
        resources:
{{ toYaml(Values.resources) | indent(12) }}
      {%- if Values.env %}
        env:
{{ toYaml(Values.env) | indent(10) }}
      {%- endif %}
        command:
          {%- for item in Values.command %}
          - {{ item | quote() }}
          {%- endfor %}
{%- if Values.resizer.enabled %}
      - name: {{ Chart.Name }}-nanny
        {%- set item = Values.resizer %}
        image: "{{ item.image.repository }}:{{ item.image.tag }}"
        imagePullPolicy: {{ item.image.pullPolicy }}
        resources:
{{ toYaml(item.resources) | indent(12) }}
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        command:
          - "/pod_nanny"
          - "--deployment={{ self.heapster__fullname() }}"
          - "--container={{ Chart.Name }}"
          {%- for item in Values.resizer.flags %}
          - {{ item | quote() }}
          {%- endfor %}
{%- endif -%}
