{%- if Values.resizer.enabled -%}
{%- if Values.rbac.create -%}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ self.heapster__fullname() }}-pod-nanny
  labels:
    app: {{ self.heapster__name() }}
    chart: {{ Chart.Name }}-{{ Chart.Version }}
    heritage: {{ Release.Service }}
    release: {{ Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ self.heapster__fullname() }}-pod-nanny
subjects:
- kind: ServiceAccount
  name: {{ self.heapster__fullname() }}
  namespace: {{ Release.Namespace }}
{%- endif -%}
{%- endif -%}
