{%- if Values.rbac.create -%}
{%- if Values.resizer.enabled -%}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: {{ self.heapster__fullname() }}-pod-nanny
  labels:
    app: {{ self.heapster__name() }}
    chart: {{ Chart.Name }}-{{ Chart.Version }}
    heritage: {{ Release.Service }}
    release: {{ Release.Name }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - "extensions"
  resources:
  - deployments
  verbs:
  - get
  - update
{%- endif -%}
{%- endif -%}
