apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ self.fullname() }}
  labels:
    app: {{ self.fullname() }}
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    release: "{{ Release.Name }}"
    heritage: "{{ Release.Service }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ self.fullname() }}
    spec:
      containers:
      - name: {{ self.fullname() }}
        image: "{{ Values.image }}"
        imagePullPolicy: {{ Values.imagePullPolicy | default("", true) | quote() }}
        env:
        - name: MARIADB_HOST
          value: {{ self.mariadb__fullname() }}
        - name: MARIADB_PORT_NUMBER
          value: "3306"
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ self.mariadb__fullname() }}
              key: mariadb-root-password
        - name: TESTLINK_USERNAME
          value: {{ Values.testlinkUsername | default("", true) | quote() }}
        - name: TESTLINK_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ self.fullname() }}
              key: testlink-password
        - name: TESTLINK_EMAIL
          value: {{ Values.testlinkEmail | default("", true) | quote() }}
        - name: TESTLINK_LANGUAGE
          value: {{ Values.testlinkLanguage | default("", true) | quote() }}
        - name: SMTP_ENABLE
          value: {{ Values.smtpEnable | default("", true) | quote() }}
        - name: SMTP_CONNECTION_MODE
          value: {{ Values.smtpConnectionMode | default("", true) | quote() }}
        - name: SMTP_HOST
          value: {{ Values.smtpHost | default("", true) | quote() }}
        - name: SMTP_PORT
          value: {{ Values.smtpPort | default("", true) | quote() }}
        - name: SMTP_USER
          value: {{ Values.smtpUser | default("", true) | quote() }}
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ self.fullname() }}
              key: smtp-password
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        livenessProbe:
          httpGet:
            path: /login.php
            port: http
          initialDelaySeconds: 120
        readinessProbe:
          httpGet:
            path: /login.php
            port: http
          initialDelaySeconds: 30
        resources:
{{ toYaml(Values.resources) | indent(10) }}
        volumeMounts:
        - name: testlink-data
          mountPath: /bitnami/testlink
        - name: apache-data
          mountPath: /bitnami/apache
      volumes:
      - name: testlink-data
      {%- if Values.persistence.enabled %}
        persistentVolumeClaim:
          claimName: {{ self.fullname() }}-testlink
      {%- else %}
        emptyDir: {}
      {%- endif %}
      - name: apache-data
      {%- if Values.persistence.enabled %}
        persistentVolumeClaim:
          claimName: {{ self.fullname() }}-apache
      {%- else %}
        emptyDir: {}
      {%- endif %}
