apiVersion: v1
kind: Service
metadata:
{%- if Values.service.annotations %}
  annotations:
{{ toYaml(Values.service.annotations) | indent(4) }}
{%- endif %}
  labels:
    app: {{ self.cluster-autoscaler__name() }}
    chart: {{ Chart.Name }}-{{ Chart.Version }}
    heritage: {{ Release.Service }}
    release: {{ Release.Name }}
  name: {{ self.cluster-autoscaler__fullname() }}
spec:
  clusterIP: "{{ Values.service.clusterIP }}"
{%- if Values.service.externalIPs %}
  externalIPs:
{{ toYaml(Values.service.externalIPs) | indent(4) }}
{%- endif %}
{%- if Values.service.loadBalancerIP %}
  loadBalancerIP: "{{ Values.service.loadBalancerIP }}"
{%- endif %}
{%- if Values.service.loadBalancerSourceRanges %}
  loadBalancerSourceRanges:
{{ toYaml(Values.service.loadBalancerSourceRanges) | indent(4) }}
{%- endif %}
  ports:
    - port: {{ Values.service.servicePort }}
      protocol: TCP
      targetPort: 8085
  selector:
    app: {{ self.cluster-autoscaler__name() }}
    release: {{ Release.Name }}
  type: "{{ Values.service.type }}"
