apiVersion: v1
kind: Secret
metadata:
  name: {{ self.fullname() }}
  labels:
    app: {{ self.fullname() }}
    chart: "{{ Chart.Name }}-{{ Chart.Version | replace("+","_") }}"
    release: "{{ Release.Name }}"
    heritage: "{{ Release.Service }}"
type: Opaque
data:
  {%- if Values.sentrySecret %}
  sentry-secret: {{ Values.sentrySecret | b64enc() | quote() }}
  {%- else %}
  sentry-secret: {{ randAlphaNum(40) | b64enc() | quote() }}
  {%- endif %}
  smtp-password: {{ Values.email.password | default("", true) | b64enc() | quote() }}
  user-password: {{ randAlphaNum(16) | b64enc() | quote() }}
