apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ self.fullname() }}-web
  labels:
    app: {{ self.fullname() }}
    chart: "{{ Chart.Name }}-{{ Chart.Version | replace("+","_") }}"
    release: "{{ Release.Name }}"
    heritage: "{{ Release.Service }}"
spec:
  replicas: {{ Values.web.replicacount }}
  template:
    metadata:
      labels:
        app: {{ self.fullname() }}
        release: "{{ Release.Name }}"
        role: web
    spec:
      containers:
      - name: {{ Chart.Name }}-web
        image: "{{ Values.image.repository }}:{{ Values.image.tag }}"
        imagePullPolicy: {{ Values.image.pullPolicy }}
        ports:
        - containerPort: {{ Values.service.internalPort }}
        env:
        - name: SENTRY_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ self.fullname() }}
              key: sentry-secret
        - name: SENTRY_DB_USER
          value: {{ Values.postgresUser | default("sentry", true) | quote() }}
        - name: SENTRY_DB_NAME
          value: {{ Values.postgresDatabase | default("sentry", true) | quote() }}
        - name: SENTRY_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ self.postgresql__fullname() }}
              key: postgres-password
        - name: SENTRY_POSTGRES_HOST
          value: {{ self.postgresql__fullname() }}
        - name: SENTRY_POSTRGES_PORT
          value: "5432"
        - name: SENTRY_REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ self.redis__fullname() }}
              key: redis-password
        - name: SENTRY_REDIS_HOST
          value: {{ self.redis__fullname() }}
        - name: SENTRY_REDIS_PORT
          value: "6379"
        - name: SENTRY_EMAIL_HOST
          value: {{ Values.email.host | default("", true) | quote() }}
        - name: SENTRY_EMAIL_PORT
          value: {{ Values.email.port | default("", true) | quote() }}
        - name: SENTRY_EMAIL_USER
          value: {{ Values.email.user | default("", true) | quote() }}
        - name: SENTRY_EMAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ self.fullname() }}
              key: smtp-password
        volumeMounts:
        - mountPath: {{ Values.persistence.filestore_dir }}
          name: sentry-data
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /_health/
            port: {{ Values.service.internalPort }}
            scheme: HTTP
          initialDelaySeconds: 50
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /_health/
            port: {{ Values.service.internalPort }}
            scheme: HTTP
          initialDelaySeconds: 50
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        resources:
{{ toYaml(Values.web.resources) | indent(12) }}
      volumes:
      - name: sentry-data
      {%- if Values.persistence.enabled %}
        persistentVolumeClaim:
          claimName: {{ self.fullname() }}
      {%- else %}
        emptyDir: {}
      {%- endif %}
