apiVersion: v1
kind: Service
metadata:
  name: {{ self.fullname() }}
  labels:
    app: {{ self.name() }}
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    release: "{{ Release.Name }}"
    heritage: "{{ Release.Service }}"
  annotations:
    service.beta.kubernetes.io/external-traffic: OnlyLocal
spec:
  type: {{ Values.serviceType }}
  {%- if Values.serviceType=="LoadBalancer" %}
  loadBalancerIP: {{ Values.suitecrmLoadBalancerIP }}
  {%- endif %}
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: https
    port: 443
    targetPort: https
  selector:
    app: {{ self.name() }}
    release: "{{ Release.Name }}"
