{%- if Values.rbac.create -%}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels: {{ self.external-dns__labels()  | indent(4) }}
    chart: {{ Chart.Name }}-{{ Chart.Version | replace("+","_") }}
  name: {{ self.external-dns__fullname() }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ self.external-dns__fullname() }}
subjects:
  - kind: ServiceAccount
    name: {{ self.external-dns__fullname() }}
    namespace: {{ Release.Namespace }}
{%- endif -%}
