{%- if (Values.aws.secret_key and Values.aws.access_key) or Values.cloudflare.api_key -%}
apiVersion: v1
kind: Secret
metadata:
  labels: {{ self.external-dns__labels()  | indent(4) }}
    chart: {{ Chart.Name }}-{{ Chart.Version | replace("+","_") }}
  name: {{ self.external-dns__fullname() }}
type: Opaque
data:
{%- if Values.aws.secret_key and Values.aws.access_key %}
  aws_access_key_id: {{ Values.aws.access_key | b64enc() | quote() }}
  aws_secret_access_key: {{ Values.aws.secret_key | b64enc() | quote() }}
{%- endif %}
{%- if Values.cloudflare.api_key %}
  cloudflare_api_key: {{ Values.cloudflare.api_key | b64enc() | quote() }}
{%- endif %}
{%- endif %}
