{%- if Values.rbac.create -%}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels: {{ self.external-dns__labels()  | indent(4) }}
    chart: {{ Chart.Name }}-{{ Chart.Version | replace("+","_") }}
  name: {{ self.external-dns__fullname() }}
{%- endif %}
