apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{ self.name() }}
    role: service
{{ self.labels__standard()  | indent(4) }}
  name: {{ self.fullname() }}
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    redis-node: "true"
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    release: "{{ Release.Name }}"
    heritage: "{{ Release.Service }}"
