apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ self.fullname() }}
  labels:
    redis-node: "true"
{{ self.labels__standard()  | indent(4) }}
spec:
  replicas: {{ Values.replicas.slave }}
  template:
    metadata:
      labels:
        name: redis
        role: replica
{{ self.labels__standard()  | indent(8) }}
    spec:
      containers:
      - name: redis
        image: "{{ Values.redis_image }}"
        resources:
{{ toYaml(Values.resources.slave) | indent(10) }}
        ports:
        - containerPort: 6379
        volumeMounts:
        - mountPath: /redis-master-data
          name: data
      volumes:
      - name: data
      {%- if Values.persistentVolume.enabled %}
        persistentVolumeClaim:
          claimName: {%- if Values.persistentVolume.existingClaim %}{{ Values.persistentVolume.existingClaim }}{%- else %}{{ self.fullname() }}{%- endif %}
      {%- else %}
        emptyDir: {}
      {%- endif -%}
