{%- if Values.networkPolicy.enabled %}
kind: NetworkPolicy
apiVersion: {{ self.postgresql__networkPolicy__apiVersion() }}
metadata:
  name: "{{ self.postgresql__fullname() }}"
  labels:
    app: {{ self.postgresql__fullname() }}
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    release: "{{ Release.Name }}"
    heritage: "{{ Release.Service }}"
spec:
  podSelector:
    matchLabels:
      app: "{{ self.postgresql__fullname() }}"
  ingress:
    # Allow inbound connections
    - ports:
      - port: 5432
    {%- if  not  Values.networkPolicy.allowExternal %}
      from:
      - podSelector:
          matchLabels:
            {{ self.postgresql__fullname() }}-client: "true"
    {%- endif %}
    # Allow prometheus scrapes
    - ports:
      - port: 9187
{%- endif %}
