apiVersion: v1
kind: Service
metadata:
  name: {{ self.postgresql__fullname() }}
  labels:
    app: {{ self.postgresql__fullname() }}
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    release: "{{ Release.Name }}"
    heritage: "{{ Release.Service }}"
{%- if Values.metrics.enabled %}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9187"
{%- endif %}
spec:
  type: {{ Values.service.type }}
  ports:
  - name: postgresql
    port: {{ Values.service.port }}
    targetPort: postgresql
{%- if Values.service.externalIPs %}
  externalIPs:
{{ toYaml(Values.service.externalIPs) | indent(4) }}
{%- endif %}
  selector:
    app: {{ self.postgresql__fullname() }}