apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ self.name() }}
    chart: {{ Chart.Name }}-{{ Chart.Version }}
    component: "{{ Values.controller.name }}"
    heritage: {{ Release.Service }}
    release: {{ Release.Name }}
  name: {{ self.controller__fullname() }}
data:
  enable-vts-status: "{{ Values.controller.stats.enabled }}"
{%- if Values.controller.config %}
{{ toYaml(Values.controller.config) | indent(2) }}
{%- endif %}
