{%- if Values.controller.stats.enabled %}
apiVersion: v1
kind: Service
metadata:
{%- if Values.controller.stats.service.annotations %}
  annotations:
{{ toYaml(Values.controller.stats.service.annotations) | indent(4) }}
{%- endif %}
  labels:
    app: {{ self.name() }}
    chart: {{ Chart.Name }}-{{ Chart.Version }}
    component: "{{ Values.controller.name }}"
    heritage: {{ Release.Service }}
    release: {{ Release.Name }}
  name: {{ self.controller__fullname() }}-stats
spec:
  clusterIP: "{{ Values.controller.stats.service.clusterIP }}"
{%- if Values.controller.stats.service.externalIPs %}
  externalIPs:
{{ toYaml(Values.controller.stats.service.externalIPs) | indent(4) }}
{%- endif %}
{%- if Values.controller.stats.service.loadBalancerIP %}
  loadBalancerIP: "{{ Values.controller.stats.service.loadBalancerIP }}"
{%- endif %}
{%- if Values.controller.stats.service.loadBalancerSourceRanges %}
  loadBalancerSourceRanges:
{{ toYaml(Values.controller.stats.service.loadBalancerSourceRanges) | indent(4) }}
{%- endif %}
  ports:
    - name: stats
      port: {{ Values.controller.stats.service.servicePort }}
      targetPort: 18080
  selector:
    app: {{ self.name() }}
    component: "{{ Values.controller.name }}"
    release: {{ Release.Name }}
  type: "{{ Values.controller.stats.service.type }}"
{%- endif %}
