{%- if Values.defaultBackend.enabled %}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ self.name() }}
    chart: {{ Chart.Name }}-{{ Chart.Version }}
    component: "{{ Values.defaultBackend.name }}"
    heritage: {{ Release.Service }}
    release: {{ Release.Name }}
  name: {{ self.defaultBackend__fullname() }}
spec:
  replicas: {{ Values.defaultBackend.replicaCount }}
  template:
    metadata:
    {%- if Values.defaultBackend.podAnnotations %}
      annotations:
{{ toYaml(Values.defaultBackend.podAnnotations) | indent(8) }}
    {%- endif %}
      labels:
        app: {{ self.name() }}
        component: "{{ Values.defaultBackend.name }}"
        release: {{ Release.Name }}
        {%- if Values.defaultBackend.podLabels %}
{{ toYaml(Values.defaultBackend.podLabels) | indent(8) }}
        {%- endif %}
    spec:
      containers:
        - name: {{ self.name() }}-{{ Values.defaultBackend.name }}
          image: "{{ Values.defaultBackend.image.repository }}:{{ Values.defaultBackend.image.tag }}"
          imagePullPolicy: "{{ Values.defaultBackend.image.pullPolicy }}"
          args:
          {%- for key, value in Values.defaultBackend.extraArgs.iteritems() %}
            {%- if value %}
            - --{{ key }}={{ value }}
            {%- else %}
            - --{{ key }}
            {%- endif %}
          {%- endfor %}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 5
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
{{ toYaml(Values.defaultBackend.resources) | indent(12) }}
    {%- if Values.defaultBackend.nodeSelector %}
      nodeSelector:
{{ toYaml(Values.defaultBackend.nodeSelector) | indent(8) }}
    {%- endif %}
    {%- if Values.defaultBackend.tolerations %}
      tolerations:
{{ toYaml(Values.defaultBackend.tolerations) | indent(8) }}
    {%- endif %}
      terminationGracePeriodSeconds: 60
{%- endif %}
