{%- if Values.tcp %}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ self.name() }}
    chart: {{ Chart.Name }}-{{ Chart.Version }}
    component: "{{ Values.controller.name }}"
    heritage: {{ Release.Service }}
    release: {{ Release.Name }}
  name: {{ self.fullname() }}-tcp
data:
{{ toYaml(Values.tcp) | indent(2) }}
{%- endif %}
