apiVersion: v1
kind: Service
metadata:
  name: {{ self.percona__fullname() }}
  labels:
    app: {{ self.percona__fullname() }}
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    release: "{{ Release.Name }}"
    heritage: "{{ Release.Service }}"
spec:
  ports:
  - name: mysql
    port: 3306
    targetPort: mysql
  selector:
    app: {{ self.percona__fullname() }}
