



---

apiVersion: v1
kind: Secret
metadata:
  name: coscale
  labels:
    app: coscale
    chart: "coscale-0.2.0"
    release: "test"
    heritage: "coscale"
type: Opaque
data:
 app_id : "TUlTU0lORw=="
 access_token : "TUlTU0lORw=="