


---

apiVersion: v1
kind: Service
metadata:
  name: heapster
  labels:
    chart: "heapster-0.2.1"
    app: test-heapster
    heritage: "heapster"
    release: "test"
spec:
  type: ClusterIP
  ports:
  - port: 8082
    targetPort: 8082
    protocol: TCP
  selector:
    app: test-heapster


---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test-heapster
  labels:
    chart: "heapster-0.2.1"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: test-heapster
    spec:
      serviceAccountName:"default"
      containers:
      - name: heapster
        image: "gcr.io/google_containers/heapster:v1.3.0"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8082
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8082
          initialDelaySeconds: 180
          timeoutSeconds: 5
        resources:
            limits: {cpu: 100m, memory: 128Mi}
            requests: {cpu: 100m, memory: 128Mi}
        command:
          - "/heapster"
          - "--source=kubernetes.summary_api:''"
      - name: heapster-nanny
        image: "gcr.io/google_containers/addon-resizer:1.7"
        imagePullPolicy: IfNotPresent
        resources:
            limits: {cpu: 50m, memory: 90Mi}
            requests: {cpu: 50m, memory: 90Mi}
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        command:
          - "/pod_nanny"
          - "--deployment=test-heapster"
          - "--container=heapster"
          - "--cpu=150m"
          - "--extra-cpu=10m"
          - "--memory=200Mi"
          - "--extra-memory=6Mi"
          - "--threshold=5"
          - "--poll-period=300000"