{%- if Values.persistence.enabled and Values.volumeMounts.apache.mountPath -%}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ self.drupal__fullname() }}-apache
  labels:
    app: {{ self.drupal__fullname() }}
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    release: "{{ Release.Name }}"
    heritage: "{{ Release.Service }}"
spec:
  accessModes:
    - {{ Values.persistence.apache.accessMode | quote() }}
  resources:
    requests:
      storage: {{ Values.persistence.apache.size | quote() }}
{%- if Values.persistence.apache.storageClass %}
{%- if ("-"==Values.persistence.apache.storageClass) %}
  storageClassName: ""
{%- else %}
  storageClassName: "{{ Values.persistence.apache.storageClass }}"
{%- endif %}
{%- endif %}
{%- endif -%}
