{%- if Values.persistence.enabled and Values.persistence.drupal.hostPath and ( not  Values.persistence.drupal.existingClaim) -%}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ self.drupal__fullname() }}-drupal
spec:
  accessModes:
    - {{ Values.persistence.drupal.accessMode | quote() }}
  capacity:
    storage: {{ Values.persistence.drupal.size | quote() }}
  hostPath:
    path: {{ Values.persistence.drupal.hostPath | quote() }}
{%- endif -%}
