apiVersion: v1
kind: Secret
metadata:
  name: {{ self.drupal__fullname() }}
  labels:
    app: {{ self.drupal__fullname() }}
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    release: "{{ Release.Name }}"
    heritage: "{{ Release.Service }}"
type: Opaque
data:
  {%- if Values.drupalPassword %}
  drupal-password: {{ Values.drupalPassword | default("", true) | b64enc() | quote() }}
  {%- else %}
  drupal-password: {{ randAlphaNum(10) | b64enc() | quote() }}
  {%- endif %}
