apiVersion: v1
kind: Service
metadata:
  name: {{ self.fullname() }}
spec:
  ports:
{%- if (Values.httpPort) %}
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
{%- elif ( not  Values.http2Port) and ( not  Values.sslPort) %}
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
{%- endif %}
{%- if (Values.http2Port) %}
  - port: 81
    targetPort: http2
    protocol: TCP
    name: http2
{%- endif %}
{%- if (Values.sslPort) %}
  - port: 443
    targetPort: https
    protocol: TCP
    name: https
{%- endif %}
  selector:
    app: {{ self.fullname() }}
  type: {{ Values.serviceType }}

