apiVersion: v1
kind: Service
metadata:
  name: {{ self.jenkins__fullname() }}-agent
  labels:
    app: {{ self.jenkins__fullname() }}
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    component: "{{ Release.Name }}-{{ Values.Master.Component }}"
spec:
  ports:
    - port: {{ Values.Master.SlaveListenerPort }}
      targetPort: {{ Values.Master.SlaveListenerPort }}
      name: slavelistener
  selector:
    component: "{{ Release.Name }}-{{ Values.Master.Component }}"
  type: ClusterIP
