apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ self.jenkins__fullname() }}-tests
data:
  run.sh: |-
    @test "Testing Jenkins UI is accessible" {
      curl --retry 12 --retry-delay 10 {{ Release.Name }}-jenkins:8080{{ Values.Master.JenkinsUriPrefix | default("", true) }}/login
    }
