# A headless service to create DNS records
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  {%- if Values.serviceAnnotations %}
{{ toYaml(Values.serviceAnnotations) | indent(4) }}
  {%- endif %}
  labels:
    app: {{ self.mongodb-replicaset__name() }}
    chart: {{ Chart.Name }}-{{ Chart.Version }}
    heritage: {{ Release.Service }}
    release: {{ Release.Name }}
  name: {{ self.mongodb-replicaset__fullname() }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: peer
      port: {{ Values.port }}
  selector:
    app: {{ self.mongodb-replicaset__name() }}
    release: {{ Release.Name }}
