{%- if (Values.auth.enabled) and ( not  Values.auth.existingKeySecret) -%}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ self.mongodb-replicaset__name() }}
    chart: {{ Chart.Name }}-{{ Chart.Version }}
    heritage: {{ Release.Service }}
    release: {{ Release.Name }}
  name: {{ self.mongodb-replicaset__keySecret() }}
type: Opaque
data:
  key.txt: {{ Values.auth.key | b64enc() }}
{%- endif -%}

