apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ self.mongodb-replicaset__name() }}
    chart: {{ Chart.Name }}-{{ Chart.Version }}
    heritage: {{ Release.Service }}
    release: {{ Release.Name }}
  name: {{ self.mongodb-replicaset__fullname() }}
data:
  mongod.conf: |
{{ toYaml(Values.configmap) | indent(4) }}
