{%- if (Values.auth.enabled) and ( not  Values.auth.existingAdminSecret) -%}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ self.mongodb-replicaset__name() }}
    chart: {{ Chart.Name }}-{{ Chart.Version }}
    heritage: {{ Release.Service }}
    release: {{ Release.Name }}
  name: {{ self.mongodb-replicaset__adminSecret() }}
type: Opaque
data:
  user: {{ Values.auth.adminUser | b64enc() }}
  password: {{ Values.auth.adminPassword | b64enc() }}
{%- endif -%}
