{%- if Values.persistence.enabled -%}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ self.prestashop__fullname() }}-prestashop
  labels:
    app: {{ self.prestashop__fullname() }}
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    release: "{{ Release.Name }}"
    heritage: "{{ Release.Service }}"
spec:
  accessModes:
    - {{ Values.persistence.prestashop.accessMode | quote() }}
  resources:
    requests:
      storage: {{ Values.persistence.prestashop.size | quote() }}
{%- if Values.persistence.prestashop.storageClass %}
{%- if ("-"==Values.persistence.prestashop.storageClass) %}
  storageClassName: ""
{%- else %}
  storageClassName: "{{ Values.persistence.prestashop.storageClass }}"
{%- endif %}
{%- endif %}
{%- endif -%}
