


---




---




---

apiVersion: v1
kind: Service
metadata:
  name: test-metabase
  labels:
    app: metabase
    chart: metabase-0.2.0
    release: test
    heritage: metabase
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: metabase
  selector:
    app: metabase
    release: test


---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test-metabase
  labels:
    app: metabase
    chart: metabase-0.2.0
    release: test
    heritage: metabase
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: metabase
        release: test
    spec:
      containers:
        - name: metabase
          image: "metabase/metabase:v0.24.2"
          imagePullPolicy: IfNotPresent
          env:
          - name: MB_JETTY_HOST
            value: "0.0.0.0"
          - name: MB_JETTY_PORT
            value: "3000"
          - name: MB_DB_TYPE
            value: h2
          - name: MB_ENCRYPTION_SECRET_KEY
            value: ""
          - name: MB_PASSWORD_COMPLEXITY
            value: normal
          - name: MB_PASSWORD_LENGTH
            value: "6"
          - name: JAVA_TIMEZONE
            value: UTC
          - name: MB_EMOJI_IN_LOGS
            value: "True"
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 120
            timeoutSeconds: 5
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            timeoutSeconds: 3
            periodSeconds: 5
          resources:
            {}