{%- if Values.alertmanager.enabled and ( empty  Values.alertmanager.configMapOverrideName) -%}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ self.prometheus__name() }}
    chart: {{ Chart.Name }}-{{ Chart.Version }}
    component: "{{ Values.alertmanager.name }}"
    heritage: {{ Release.Service }}
    release: {{ Release.Name }}
  name: {{ self.prometheus__alertmanager__fullname() }}
data:
{{ toYaml(Values.alertmanagerFiles) | indent(2) }}
{%- endif %}
