{%- if Values.rbac.create %}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ self.prometheus__name() }}
    chart: {{ Chart.Name }}-{{ Chart.Version }}
    component: "{{ Values.alertmanager.name }}"
    heritage: {{ Release.Service }}
    release: {{ Release.Name }}
  name: {{ self.prometheus__alertmanager__fullname() }}
{%- endif %}
