{%- if Values.alertmanager.enabled and Values.alertmanager.persistentVolume.enabled -%}
{%- if  not  Values.alertmanager.persistentVolume.existingClaim -%}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  {%- if Values.alertmanager.persistentVolume.annotations %}
  annotations:
{{ toYaml(Values.alertmanager.persistentVolume.annotations) | indent(4) }}
  {%- endif %}
  labels:
    app: {{ self.prometheus__name() }}
    chart: {{ Chart.Name }}-{{ Chart.Version }}
    component: "{{ Values.alertmanager.name }}"
    heritage: {{ Release.Service }}
    release: {{ Release.Name }}
  name: {{ self.prometheus__alertmanager__fullname() }}
spec:
  accessModes:
{{ toYaml(Values.alertmanager.persistentVolume.accessModes) | indent(4) }}
{%- if Values.alertmanager.persistentVolume.storageClass %}
{%- if ("-"==Values.alertmanager.persistentVolume.storageClass) %}
  storageClassName: ""
{%- else %}
  storageClassName: "{{ Values.alertmanager.persistentVolume.storageClass }}"
{%- endif %}
{%- endif %}
  resources:
    requests:
      storage: "{{ Values.alertmanager.persistentVolume.size }}"
{%- endif -%}
{%- endif -%}
