{%- if Values.rbac.create %}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app: {{ self.prometheus__name() }}
    chart: {{ Chart.Name }}-{{ Chart.Version }}
    component: "{{ Values.kubeStateMetrics.name }}"
    heritage: {{ Release.Service }}
    release: {{ Release.Name }}
  name: {{ self.prometheus__kubeStateMetrics__fullname() }}
subjects:
  - kind: ServiceAccount
    name: {{ self.prometheus__kubeStateMetrics__fullname() }}
    namespace: {{ Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ self.prometheus__kubeStateMetrics__fullname() }}
{%- endif %}
