{%- if Values.kubeStateMetrics.enabled -%}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ self.prometheus__name() }}
    chart: {{ Chart.Name }}-{{ Chart.Version }}
    component: "{{ Values.kubeStateMetrics.name }}"
    heritage: {{ Release.Service }}
    release: {{ Release.Name }}
  name: {{ self.prometheus__kubeStateMetrics__fullname() }}
spec:
  replicas: {{ Values.kubeStateMetrics.replicaCount }}
  template:
    metadata:
    {%- if Values.kubeStateMetrics.podAnnotations %}
      annotations:
{{ toYaml(Values.kubeStateMetrics.podAnnotations) | indent(8) }}
    {%- endif %}
      labels:
        app: {{ self.prometheus__name() }}
        component: "{{ Values.kubeStateMetrics.name }}"
        release: {{ Release.Name }}
    spec:
      serviceAccountName: {%- if Values.rbac.create %}{{ self.prometheus__kubeStateMetrics__fullname() }}{%- else %}"{{ Values.kubeStateMetrics.serviceAccountName }}"{%- endif %}
      containers:
        - name: {{ self.prometheus__name() }}-{{ Values.kubeStateMetrics.name }}
          image: "{{ Values.kubeStateMetrics.image.repository }}:{{ Values.kubeStateMetrics.image.tag }}"
          imagePullPolicy: "{{ Values.kubeStateMetrics.image.pullPolicy }}"
          ports:
            - name: metrics
              containerPort: 8080
          resources:
{{ toYaml(Values.kubeStateMetrics.resources) | indent(12) }}
    {%- if Values.kubeStateMetrics.nodeSelector %}
      nodeSelector:
{{ toYaml(Values.kubeStateMetrics.nodeSelector) | indent(8) }}
    {%- endif %}
{%- endif %}
