{%- if Values.nodeExporter.enabled -%}
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: {{ self.prometheus__name() }}
    chart: {{ Chart.Name }}-{{ Chart.Version }}
    component: "{{ Values.nodeExporter.name }}"
    heritage: {{ Release.Service }}
    release: {{ Release.Name }}
  name: {{ self.prometheus__nodeExporter__fullname() }}
spec:
  template:
    metadata:
    {%- if Values.nodeExporter.podAnnotations %}
      annotations:
{{ toYaml(Values.nodeExporter.podAnnotations) | indent(8) }}
    {%- endif %}
      labels:
        app: {{ self.prometheus__name() }}
        component: "{{ Values.nodeExporter.name }}"
        release: {{ Release.Name }}
    spec:
      serviceAccountName: {%- if Values.rbac.create %}{{ self.prometheus__nodeExporter__fullname() }}{%- else %}"{{ Values.nodeExporter.serviceAccountName }}"{%- endif %}
      containers:
        - name: {{ self.prometheus__name() }}-{{ Values.nodeExporter.name }}
          image: "{{ Values.nodeExporter.image.repository }}:{{ Values.nodeExporter.image.tag }}"
          imagePullPolicy: "{{ Values.nodeExporter.image.pullPolicy }}"
          args:
            - --collector.procfs=/host/proc
            - --collector.sysfs=/host/sys
          {%- for key, value in Values.nodeExporter.extraArgs.iteritems() %}
            - --{{ key }}={{ value }}
          {%- endfor %}
          ports:
            - name: metrics
              containerPort: 9100
              hostPort: {{ Values.nodeExporter.service.hostPort }}
          resources:
{{ toYaml(Values.nodeExporter.resources) | indent(12) }}
          volumeMounts:
            - name: proc
              mountPath: /host/proc
              readOnly:  true
            - name: sys
              mountPath: /host/sys
              readOnly: true
          {%- for item in Values.nodeExporter.extraHostPathMounts %}
            - name: {{ item.name }}
              mountPath: {{ item.mountPath }}
              readOnly: {{ item.readOnly }}
          {%- endfor %}
      hostNetwork: true
      hostPID: true
    {%- if Values.nodeExporter.tolerations %}
      tolerations:
{{ toYaml(Values.nodeExporter.tolerations) | indent(8) }}
    {%- endif %}
    {%- if Values.nodeExporter.nodeSelector %}
      nodeSelector:
{{ toYaml(Values.nodeExporter.nodeSelector) | indent(8) }}
    {%- endif %}
      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: sys
          hostPath:
            path: /sys
      {%- for item in Values.nodeExporter.extraHostPathMounts %}
        - name: {{ item.name }}
          hostPath:
            path: {{ item.hostPath }}
      {%- endfor %}
{%- endif -%}
