{%- if Values.networkPolicy.enabled %}
apiVersion: {{ self.prometheus__networkPolicy__apiVersion() }}
kind: NetworkPolicy
metadata:
  name: {{ self.prometheus__server__fullname() }}
  labels:
    app: {{ self.prometheus__name() }}
    chart: {{ Chart.Name }}-{{ Chart.Version }}
    component: "{{ Values.server.name }}"
    heritage: {{ Release.Service }}
    release: {{ Release.Name }}
spec:
  podSelector:
    matchLabels:
      app: {{ self.prometheus__name() }}
      component: "{{ Values.server.name }}"
      release: {{ Release.Name }}
  ingress:
    - ports:
      - port: 9090
{%- endif %}
