{%- if ( empty  Values.server.configMapOverrideName) -%}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ self.prometheus__name() }}
    chart: {{ Chart.Name }}-{{ Chart.Version }}
    component: "{{ Values.server.name }}"
    heritage: {{ Release.Service }}
    release: {{ Release.Name }}
  name: {{ self.prometheus__server__fullname() }}
data:
{{ toYaml(Values.serverFiles) | indent(2) }}
{%- endif %}
