{%- if Values.ssl.enabled %}
apiVersion: v1
kind: Secret
metadata:
  name: {{ self.metabase__fullname() }}-ssl
  labels:
    app: {{ self.metabase__name() }}
    chart: {{ Chart.Name }}-{{ Chart.Version | replace("+","_") }}
    release: {{ Release.Name }}
    heritage: {{ Release.Service }}
type: Opaque
data:
  keystore: {{ Values.ssl.keystore | b64enc() | quote() }}
  password: {{ Values.ssl.keyStorePassword | b64enc() | quote() }}
{%- endif %}
