
apiVersion: v1
kind: Service
metadata:
  name: test-uchiwa
  labels:
    heritage: "uchiwa"
    release: "test"
    chart: "uchiwa-0.2.2"
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: test-uchiwa


---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test-uchiwa
  labels:
    heritage: "uchiwa"
    release: "test"
    chart: "uchiwa-0.2.2"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: test-uchiwa
        release: "test"
    spec:
      containers:
      - name: uchiwa
        image: "sstarcher/uchiwa:0.22"
        imagePullPolicy: IfNotPresent
        resources:
          limits: {memory: 50Mi}
          requests: {cpu: 10m, memory: 50Mi}
        env:
          - name: UCHIWA_BIND
            value: "0.0.0.0"
          - name: UCHIWA_SERVICE_PORT
            value: "3000"
          - name: UCHIWA_REFRESH
            value: "10"
          - name: UCHIWA_LOG_LEVEL
            value: "info"
          - name: SENSU_DC_NAME
            value: "Sensu"
          - name: SENSU_HOSTNAME
            value: test-sensu
        livenessProbe:
          httpGet:
            path: /
            port: 3000
        readinessProbe:
          httpGet:
            path: /
            port: 3000
        ports:
        - containerPort: 3000