
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: test-desktop
 labels:
    app: test-desktop
    chart: "desktop-0.6.13"
    release: "test"
    heritage: "desktop"spec:
  rules:
    - host: desktop.local
      http:
        paths:
          - path: /
            backend:
              serviceName: test-desktop
              servicePort: http

---

apiVersion: v1
kind: Secret
metadata:
  name: test-desktop
  labels:
    app: test-desktop
    chart: "desktop-0.6.13"
    release: "test"
    heritage: "desktop"
type: Opaque
data:
  password: "MTIzNDU2"



---

apiVersion: v1
kind: Service
metadata:
  name: test-desktop
  labels:
    app: test-desktop
    chart: "desktop-0.6.13"
    release: "test"
    heritage: "desktop"
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: test-desktop


---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test-desktop
  labels:
    app: test-desktop
    chart: "desktop-0.6.13"
    release: "test"
    heritage: "desktop"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: test-desktop
    spec:
      containers:
      - name: test-desktop
        image: "192.168.18.250:5002/ufleet/desktop:v1.0.1"
        imagePullPolicy: ""
        env:
        - name: EXTJS_VERSION
          value: "4.0"
        - name: ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: test-desktop
              key: password
        ports:
        - name: http
          containerPort: 80

        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 120
          timeoutSeconds: 5
          failureThreshold: 6
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          timeoutSeconds: 3
          periodSeconds: 5
        volumeMounts:
        - mountPath: /root/volumes
          name: data
          subPath: cache
        resources:
          limits: {cpu: 1000m, memory: 1024Mi}
          requests: {cpu: 300m, memory: 512Mi}
      volumes:
      - name: data
        emptyDir: {}