apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ self.fullname() }}
  labels:
    app: {{ self.fullname() }}
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    release: "{{ Release.Name }}"
    heritage: "{{ Release.Service }}"
spec:
  template:
    metadata:
      labels:
        app: {{ self.fullname() }}
    spec:
      containers:
      - name: {{ self.fullname() }}
        image: "{{ Values.image }}"
        imagePullPolicy: {{ Values.imagePullPolicy | default("", true) | quote() }}
        env:
        - name: POSTGRESQL_HOST
          value: {{ self.postgresql__fullname() }}
        - name: POSTGRESQL_PORT_NUMBER
          value: "5432"
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ self.postgresql__fullname() }}
              key: postgres-password
        - name: ODOO_EMAIL
          value: {{ Values.odooEmail | default("", true) | quote() }}
        - name: ODOO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ self.fullname() }}
              key: odoo-password
        - name: SMTP_HOST
          value: {{ Values.smtpHost | default("", true) | quote() }}
        - name: SMTP_PORT
          value: {{ Values.smtpPort | default("", true) | quote() }}
        - name: SMTP_USER
          value: {{ Values.smtpUser | default("", true) | quote() }}
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ self.fullname() }}
              key: smtp-password
        - name: SMTP_PROTOCOL
          value: {{ Values.smtpProtocol | default("", true) | quote() }}
        ports:
        - name: http
          containerPort: 8069
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 180
          timeoutSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          timeoutSeconds: 1
        resources:
{{ toYaml(Values.resources) | indent(10) }}
        volumeMounts:
        - name: odoo-data
          mountPath: /bitnami/odoo
      volumes:
      - name: odoo-data
      {%- if Values.persistence.enabled %}
        persistentVolumeClaim:
          claimName: {{ self.fullname() }}
      {%- else %}
        emptyDir: {}
      {%- endif %}
