apiVersion: v1
kind: Secret
metadata:
  name: {{ self.coscale__name() }}
  labels:
    app: {{ self.coscale__name() }}
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    release: "{{ Release.Name }}"
    heritage: "{{ Release.Service }}"
type: Opaque
data:
 app_id : {{ Values.coscale.appId | default("MISSING", true) | b64enc() | quote() }}
 access_token : {{ Values.coscale.accessToken | default("MISSING", true) | b64enc() | quote() }}