{%- if self.magento__host() -%}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ self.magento__fullname() }}
  labels:
    app: {{ self.magento__fullname() }}
    chart: "{{ Chart.Name }}-{{ Chart.Version }}"
    release: "{{ Release.Name }}"
    heritage: "{{ Release.Service }}"
spec:
  template:
    metadata:
      labels:
        app: {{ self.magento__fullname() }}
    spec:
      containers:
      - name: {{ self.magento__fullname() }}
        image: "{{ Values.image }}"
        imagePullPolicy: {{ Values.imagePullPolicy | default("", true) | quote() }}
        env:
        - name: MARIADB_HOST
          value: {{ self.magento__mariadb__fullname() }}
        - name: MARIADB_PORT_NUMBER
          value: "3306"
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ self.magento__mariadb__fullname() }}
              key: mariadb-root-password
        - name: MAGENTO_HOST
          value: {{ self.magento__host()  | quote() }}
        - name: MAGENTO_USERNAME
          value: {{ Values.magentoUsername | default("", true) | quote() }}
        - name: MAGENTO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ self.magento__fullname() }}
              key: magento-password
        - name: MAGENTO_EMAIL
          value: {{ Values.magentoEmail | default("", true) | quote() }}
        - name: MAGENTO_ADMINURI
          value: {{ Values.magentoAdminUri | default("", true) | quote() }}
        - name: MAGENTO_FIRSTNAME
          value: {{ Values.magentoFirstName | default("", true) | quote() }}
        - name: MAGENTO_LASTNAME
          value: {{ Values.magentoLastName | default("", true) | quote() }}
        - name: MAGENTO_MODE
          value: {{ Values.magentoMode | default("", true) | quote() }}
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        livenessProbe:
          httpGet:
            path: /index.php
            port: http
            httpHeaders:
            - name: Host
              value: {{ self.magento__host()  | quote() }}
          initialDelaySeconds: 420
          timeoutSeconds: 5
          failureThreshold: 6
        readinessProbe:
          httpGet:
            path: /index.php
            port: http
            httpHeaders:
            - name: Host
              value: {{ self.magento__host()  | quote() }}
          initialDelaySeconds: 30
          timeoutSeconds: 3
          periodSeconds: 5
        resources:
{{ toYaml(Values.resources) | indent(10) }}
        volumeMounts:
        - name: magento-data
          mountPath: /bitnami/magento
        - name: apache-data
          mountPath: /bitnami/apache
      volumes:
      - name: magento-data
      {%- if Values.persistence.enabled %}
        persistentVolumeClaim:
          claimName: {{ self.magento__fullname() }}-magento
      {%- else %}
        emptyDir: {}
      {%- endif %}
      - name: apache-data
      {%- if Values.persistence.enabled %}
        persistentVolumeClaim:
          claimName: {{ self.magento__fullname() }}-apache
      {%- else %}
        emptyDir: {}
      {%- endif %}
{%- endif -%}
